/**
 * Catalog headline numbers — client-safe and constant-size.
 *
 * Import this instead of `@/lib/effect-index` when all you need is a
 * count. The index is ~772 KB of metadata that the browser must download,
 * parse and hold in memory; this is ~1 KB and does not grow with the
 * catalog.
 *
 *   @/lib/effects        5.6 MB   full catalog     (server / build only)
 *   @/lib/effect-index   772 KB   searchable rows  (only /library, ⌘K)
 *   @/lib/catalog-stats    1 KB   counts           (anywhere)
 *
 * The landing page previously imported the index purely to render
 * "4,308 effects" and a per-category tally, which is what made `/` — the
 * highest-traffic page — pay for the whole catalog.
 *
 * Regenerated by scripts/build-catalog-stats.mts on every build.
 */

import STATS from './generated-catalog-stats.json'
import type { EffectCategory } from './effect-types'

interface CatalogStats {
  total: number
  css: number
  shader: number
  featured: number
  byCategory: Record<string, number>
}

const stats = STATS as CatalogStats

/** Every effect in the catalog, hand-written and generated. */
export const TOTAL_COUNT = stats.total

/**
 * The effects that are CSS, and the ones that run.
 *
 * Both are here rather than only the total, because the total on its own
 * invites the sentence that used to be on `/docs`: "N CSS effects", where N
 * was every effect in the catalog. That was true until the shader tier
 * landed and false afterwards, with nothing to notice — a count that is
 * right and a noun that is wrong is the worst shape a claim can take.
 */
export const CSS_COUNT = stats.css
export const SHADER_COUNT = stats.shader

/** Hand-crafted (curated) effects — what the "Featured" filter shows. */
export const FEATURED_COUNT = stats.featured

/** How many effects live in a category. */
export function countByCategory(category: EffectCategory): number {
  return stats.byCategory[category] ?? 0
}

/** Category tallies as entries, in CATEGORIES order. Handy for chip rows. */
export function categoryCounts(
  categories: readonly EffectCategory[],
): Array<{ category: EffectCategory; count: number }> {
  return categories.map((category) => ({ category, count: countByCategory(category) }))
}
