import 'server-only'

import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * The Figma icon sheets' manifest, or null when none has been built.
 *
 * Read from disk rather than imported, for the reason `figma-kit.ts` gives:
 * a static import makes the file mandatory, and a page that refuses to compile
 * because a generated directory is missing is a worse failure than a page
 * that quietly omits one section.
 *
 * Unlike the block kit these sheets are regenerated by every `prebuild`, so
 * in a normal build the manifest always exists. The null case is a fresh clone
 * running `next dev` before its first prebuild.
 */

export interface FigmaIconFile {
  category: string
  slug: string
  label: string
  file: string
  icons: number
  bytes: number
  /** A row of icons as inline SVG in `currentColor`. Generated, never user input. */
  sample: string
}

export interface FigmaIcons {
  lucideVersion: string
  categoriesFetchedAt: string
  license: string
  /** Distinct icons. */
  icons: number
  /** Icon placements across all sheets; an icon in two categories counts twice. */
  placements: number
  excluded: number
  note: string
  files: FigmaIconFile[]
}

function load(): FigmaIcons | null {
  const path = join(process.cwd(), 'public', 'figma', 'icons', 'manifest.json')
  if (!existsSync(path)) return null
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as FigmaIcons
  } catch {
    return null
  }
}

export const FIGMA_ICONS: FigmaIcons | null = load()

export function figmaIconHref(file: FigmaIconFile): string {
  return `/figma/icons/${file.file}`
}
