import { test } from 'node:test'
import assert from 'node:assert/strict'

import {
  FRAMEWORK_CAVEAT,
  FRAMEWORK_COUNT,
  FRAMEWORK_LINE,
  FRAMEWORK_STORIES,
  SAMPLE_BLOCK_ID,
  SAMPLE_EFFECT_ID,
  getFrameworkStory,
} from './frameworks'
import { FRAMEWORKS, exportEffect, isFrameworkId } from './export'
import { isMarkupFramework } from './blocks/markup-frameworks'
import { getBundledEffect } from './bundled-effects'

/**
 * What is actually at risk here is not the data — it is the agreement
 * between the data and the converters.
 *
 * `/frameworks/[slug]` prints a support claim next to output generated by
 * the real builder. The failure mode worth catching is the two disagreeing:
 * a row promising a conversion for a target nothing can build, or a
 * converter shipping with no page offering it. Both pass tsc happily, and
 * both are the kind of over-claim this whole area of the codebase keeps
 * arguing against in docblocks.
 */

test('every story is reachable at its own slug', () => {
  for (const story of FRAMEWORK_STORIES) {
    assert.equal(getFrameworkStory(story.id), story)
    // The id is a URL segment. Anything needing encoding would ship a
    // route that does not match the link pointing at it.
    assert.match(story.id, /^[a-z][a-z0-9-]*$/, `${story.id} is not URL-safe`)
  }
  assert.equal(getFrameworkStory('nope'), undefined)
  assert.equal(FRAMEWORK_COUNT, FRAMEWORK_STORIES.length)
})

test('slugs are unique', () => {
  const ids = FRAMEWORK_STORIES.map((f) => f.id)
  assert.equal(new Set(ids).size, ids.length)
})

test('an effects claim and an effects converter agree', () => {
  for (const story of FRAMEWORK_STORIES) {
    if (story.effects === 'none') {
      // Astro. The page renders a "not in this framework" section instead
      // of a code block, and it must not be offered a builder.
      assert.equal(
        story.exportTarget,
        null,
        `${story.id} says effects: 'none' but names an exportTarget`,
      )
      continue
    }

    assert.ok(story.exportTarget, `${story.id} claims effects but has no converter`)
    assert.ok(
      isFrameworkId(story.exportTarget),
      `${story.id} names an unknown converter: ${story.exportTarget}`,
    )
    // 'markup' is not a thing at the effect rung — an effect is CSS, so it
    // either converts or it is not offered.
    assert.equal(
      story.effects,
      'full',
      `${story.id} claims partial effect support, which does not exist`,
    )
  }
})

test('a blocks markup claim and a wrapper agree', () => {
  for (const story of FRAMEWORK_STORIES) {
    if (story.blocks === 'markup') {
      assert.ok(story.markupTarget, `${story.id} claims markup but has no wrapper`)
      assert.ok(
        isMarkupFramework(story.markupTarget),
        `${story.id} names an unknown wrapper: ${story.markupTarget}`,
      )
    } else {
      /*
       * 'full' and 'none' both mean no wrapper, for opposite reasons —
       * React and Tailwind blocks already are what they would convert to,
       * and styled-components has nothing at this rung. Either way, a
       * wrapper here would put a second file format on the page beside a
       * claim that does not mention one.
       */
      assert.equal(
        story.markupTarget,
        null,
        `${story.id} says blocks: '${story.blocks}' but names a markupTarget`,
      )
    }
  }
})

test('every converter has a page offering it', () => {
  /*
   * The direction that actually rots.
   *
   * Adding a builder to `lib/export` and forgetting the story leaves a
   * target the CLI emits and no page mentions, which is the original
   * complaint — a capability nobody is credited for. 'css' is the exception
   * on purpose: it is the plain-stylesheet fallback and the HTML + CSS
   * story covers it, so there is no separate page to want.
   */
  const offered = new Set(
    FRAMEWORK_STORIES.map((f) => f.exportTarget).filter((t) => t !== null),
  )
  for (const framework of FRAMEWORKS) {
    if (framework.id === 'css') continue
    assert.ok(
      offered.has(framework.id),
      `${framework.id} converts but no /frameworks page offers it`,
    )
  }
})

test('the sample effect exists and converts for every target', () => {
  const effect = getBundledEffect(SAMPLE_EFFECT_ID)
  assert.ok(effect, `SAMPLE_EFFECT_ID "${SAMPLE_EFFECT_ID}" is not a bundled effect`)

  for (const story of FRAMEWORK_STORIES) {
    if (!story.exportTarget) continue
    const out = exportEffect(
      {
        id: effect.id,
        name: effect.name,
        description: effect.description,
        category: effect.category,
        html: effect.html,
        css: effect.css,
      },
      story.exportTarget,
    )
    assert.ok(out.files.length > 0, `${story.id} produced no file`)
    for (const file of out.files) {
      assert.ok(file.code.trim().length > 0, `${story.id}: ${file.path} is empty`)
    }
    // The page prints these as "what to know before you paste it". An empty
    // list would render a heading over nothing for a lossy target.
    if (story.exportTarget !== 'html') {
      assert.ok(out.notes.length > 0, `${story.id} converted with no notes`)
    }
  }
})

test('each page has the per-framework copy it needs', () => {
  for (const story of FRAMEWORK_STORIES) {
    assert.ok(story.headline.length > 0, `${story.id} has no headline`)
    assert.ok(
      story.headline.toLowerCase().includes(story.label.toLowerCase()) ||
        story.label === 'HTML + CSS',
      `${story.id}'s headline does not name the framework`,
    )
    assert.ok(story.ecosystem.length > 0, `${story.id} names no toolchain`)
    assert.ok(story.setup.length > 0, `${story.id} has no setup steps`)
    assert.ok(story.keywords.length > 0, `${story.id} answers no query`)
  }
})

test('the Astro page does not promise effects', () => {
  /*
   * Named rather than folded into the loop above, because it is the one
   * claim in this file somebody would "fix" by making the headlines
   * parallel — and a parallel Astro headline is a false one.
   */
  const astro = getFrameworkStory('astro')
  assert.ok(astro)
  assert.equal(astro.effects, 'none')
  assert.ok(
    !/effect/i.test(astro.headline),
    'the Astro headline mentions effects, which it does not ship',
  )
})

test('the caveat and the one-liner stay derived', () => {
  assert.match(FRAMEWORK_CAVEAT, /markup/i)
  for (const story of FRAMEWORK_STORIES) {
    assert.ok(FRAMEWORK_LINE.includes(story.label), `${story.label} is not in the line`)
  }
})

test('the sample block id is a plain id', () => {
  // The markup itself is asserted in `blocks/markup-frameworks.test.ts`;
  // reading the generated JSON here would drag ~490 KB into the test run
  // for no extra coverage. What matters is that it is usable as a filename
  // and a URL segment, which is what the page does with it.
  assert.match(SAMPLE_BLOCK_ID, /^[a-z][a-z0-9-]*$/)
})
