/**
 * Per-framework code generators.
 *
 * Every generator takes the same input — an effect's markup plus its
 * (possibly customized) CSS — and produces paste-and-run source. The
 * guiding constraint is that the output must work with no build config
 * beyond what the framework already provides: no CSS modules to wire up,
 * no PostCSS plugin to install, no class-name collisions to resolve.
 *
 * That's why React/Vue/Svelte all emit a single self-contained file with
 * the styles inline. The one exception is styled-components, where the
 * idiomatic form genuinely is a transformed stylesheet — so there we do
 * the real work: hoist `@keyframes` into `keyframes` helpers and rewrite
 * the root selector to `&` so the CSS nests inside the component.
 */

import {
  type HtmlElement,
  classList,
  parseHtml,
  removeAttr,
  renderMarkup,
  singleRoot,
  walkElements,
} from './html-parse'
import {
  atBlockToCss,
  declarationsToCss,
  parseCss,
  ruleToCss,
  splitSelectorList,
} from './css-parse'

/** "btn-gradient" → "BtnGradient"; always a valid JS identifier. */
export function pascalCase(id: string): string {
  const parts = id.split(/[^A-Za-z0-9]+/).filter(Boolean)
  let name = parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('')
  if (!name || /^[0-9]/.test(name)) name = `Effect${name}`
  return name
}

/** Indent every non-empty line of a block. */
function indentBlock(text: string, indent: string): string {
  return text
    .split('\n')
    .map((line) => (line.trim() ? indent + line : ''))
    .join('\n')
}

/**
 * Strip the common leading whitespace from a block, so re-indenting it
 * somewhere else doesn't compound the original indentation. Source CSS is
 * authored inline (`@keyframes x { 0% { … }`), which leaves the first line
 * flush and the rest indented — that reads badly once hoisted.
 */
function dedent(text: string): string {
  const lines = text.replace(/\t/g, '  ').split('\n')
  let min = Infinity
  for (const line of lines.slice(1)) {
    if (!line.trim()) continue
    min = Math.min(min, line.length - line.trimStart().length)
  }
  if (!Number.isFinite(min) || min === 0) return text
  return lines
    .map((line, i) => (i === 0 ? line : line.slice(min)))
    .join('\n')
}

/** Make CSS safe to embed in a JS template literal. */
function escapeTemplateLiteral(css: string): string {
  return css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

/* ------------------------------------------------------------------ *
 *  React
 * ------------------------------------------------------------------ */

export interface FrameworkInput {
  id: string
  name: string
  description: string
  html: string
  css: string
  /**
   * The line in the generated file's banner that says where this came
   * from. Defaults to the catalog's phrasing, which is right for every
   * caller but one: /tools/convert runs a visitor's own markup through
   * these builders, and telling them their paste came "from the X effect"
   * would be a lie printed at the top of their file.
   */
  provenance?: string
}

/** The banner's source line — see `FrameworkInput.provenance`. */
function provenanceOf(input: FrameworkInput): string {
  return input.provenance ?? `Generated by Hoverlab from the "${input.id}" effect.`
}

export function buildReact(input: FrameworkInput): { code: string; notes: string[] } {
  const componentName = pascalCase(input.id)
  const nodes = parseHtml(input.html)
  const jsx = renderMarkup(nodes, {
    jsx: true,
    indent: input.css.trim() ? '      ' : '    ',
    reactUncontrolled: true,
  })

  /*
   * Markup with no stylesheet returns the markup, not an empty <style>.
   *
   * Every catalog effect has CSS, so this branch never fired until
   * /tools/convert started feeding this builder a bare paste of someone's
   * HTML — the single commonest thing anyone converts to JSX. An empty
   * style tag and a fragment wrapper around one element are noise in that
   * file, and noise in generated code reads as a bug in the generator.
   */
  const css = input.css.trim()

  // A fragment is only dropped when it would wrap a single element and
  // nothing else — siblings still need one, or the return is not an
  // expression.
  const body = css
    ? `    <>
      <style>{\`
${indentBlock(escapeTemplateLiteral(css), '')}
      \`}</style>
${jsx}
    </>`
    : singleRoot(nodes)
      ? jsx
      : `    <>\n${indentBlock(jsx, '  ')}\n    </>`

  const cssNote = css
    ? `
 *
 * The CSS ships in a <style> tag so the class selectors resolve exactly as
 * they do in the original. If you render this component many times on one
 * page, lift the <style> into a global stylesheet instead so the rules are
 * only parsed once.`
    : ''

  const code = `/**
 * ${componentName} — ${input.name}
 * ${input.description}
 *
 * ${provenanceOf(input)} Drop this file into any React app (Next.js, Vite,
 * CRA, Remix) and import it — no extra dependencies, no build
 * configuration.${cssNote}
 */
export function ${componentName}() {
  return (
${body}
  )
}

export default ${componentName}
`

  return {
    code,
    notes: [
      'Valid as both .tsx and .jsx — there are no type annotations to strip.',
      'Inputs render uncontrolled (defaultChecked) so React does not warn about a value without an onChange handler.',
    ],
  }
}

/* ------------------------------------------------------------------ *
 *  Vue
 * ------------------------------------------------------------------ */

export function buildVue(input: FrameworkInput): { code: string; notes: string[] } {
  const template = renderMarkup(parseHtml(input.html), { indent: '  ' })
  const css = input.css.trim()

  const code = `<!--
  ${input.name} — ${input.description}
  ${provenanceOf(input)}
-->
<template>
${template}
</template>
${
  css
    ? `
<style scoped>
${css}
</style>
`
    : ''
}`

  const notes = css
    ? [
        'Styles are scoped, so they cannot leak into the rest of your app. Vue rewrites @keyframes names inside scoped blocks automatically.',
        'If you need to style something rendered by a child component, wrap that selector in :deep().',
      ]
    : ['No stylesheet was given, so the component is template-only.']

  return { code, notes }
}

/* ------------------------------------------------------------------ *
 *  Svelte
 * ------------------------------------------------------------------ */

export function buildSvelte(input: FrameworkInput): { code: string; notes: string[] } {
  const markup = renderMarkup(parseHtml(input.html), { indent: '' })
  const css = input.css.trim()

  const code = `<!--
  ${input.name} — ${input.description}
  ${provenanceOf(input)}
-->
${markup}
${
  css
    ? `
<style>
${css}
</style>
`
    : ''
}`

  const notes = css
    ? [
        "Svelte scopes component styles and prunes selectors it cannot statically match. If the compiler reports an unused selector, wrap it in :global(...) — that is expected for rules targeting pseudo-elements on dynamically added markup.",
      ]
    : ['No stylesheet was given, so the component is markup-only.']

  return { code, notes }
}

/* ------------------------------------------------------------------ *
 *  styled-components
 * ------------------------------------------------------------------ */

/**
 * Rewrite a stylesheet so it can nest inside a single styled component.
 *
 * `.fx-btn` becomes `&`, `.fx-btn:hover` becomes `&:hover`, `.fx-btn .knob`
 * becomes `& .knob`. Rules that never mention the root class are scoped
 * under `& ` so they cannot escape the component.
 */
function scopeToRoot(css: string, rootClass: string | null): string {
  const parsed = parseCss(css)
  const out: string[] = []

  for (const rule of parsed.rules) {
    const selectors = rule.selectors.map((selector) => {
      if (!rootClass) return `& ${selector}`
      const escaped = rootClass.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
      // `.root` at the start, followed by end-of-selector or any character
      // that cannot continue an identifier.
      const atStart = new RegExp(`^\\.${escaped}(?![-\\w])`)
      if (atStart.test(selector)) {
        const rest = selector.replace(atStart, '')
        return rest.length === 0 ? '&' : `&${rest}`
      }
      return `& ${selector}`
    })

    // A rule that is exactly the root emits its declarations bare — that
    // is the idiomatic styled-components form, and `& { … }` around them
    // is noise.
    const scoped = { ...rule, selectors }
    const text =
      selectors.length === 1 && selectors[0] === '&'
        ? declarationsToCss(rule.declarations, '')
        : ruleToCss(scoped)

    if (rule.atContext.length) {
      out.push(`${rule.atContext.join(' ')} {\n${indentBlock(text, '  ')}\n}`)
    } else {
      out.push(text)
    }
  }

  return out.join('\n\n')
}

export function buildStyledComponents(
  input: FrameworkInput,
): { code: string; notes: string[] } {
  const componentName = pascalCase(input.id)
  const roots = parseHtml(input.html)
  const root = singleRoot(roots)
  const rootClasses = root ? classList(root) : []
  const rootClass = rootClasses[0] ?? null
  const tag = root?.tag ?? 'div'
  const notes: string[] = []

  const parsed = parseCss(input.css)

  /* Hoist @keyframes into `keyframes` helpers so the animation names are
   * scoped to this component instead of leaking into the global sheet. */
  const keyframeBlocks = parsed.atBlocks.filter((b) => b.name === 'keyframes')
  const otherBlocks = parsed.atBlocks.filter((b) => b.name !== 'keyframes')
  const keyframeVars = new Map<string, string>()
  for (const block of keyframeBlocks) {
    const original = block.params.trim()
    if (!original) continue
    const varName = `${pascalCase(original).charAt(0).toLowerCase()}${pascalCase(original).slice(1)}Frames`
    keyframeVars.set(original, varName)
  }

  // Strip the keyframes from the CSS body before scoping — they become
  // separate declarations rather than nested rules.
  let body = scopeToRoot(input.css, rootClass)

  // Any remaining non-keyframe at-blocks (@font-face, @property) have to
  // stay global; styled-components can't nest them meaningfully.
  const globalBlocks = otherBlocks.map((b) => atBlockToCss(b)).join('\n\n')

  body = escapeTemplateLiteral(body)

  // Re-introduce the interpolations for the hoisted keyframes.
  for (const [original, varName] of keyframeVars) {
    const wordBoundary = new RegExp(`(^|[\\s:,])${original.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?=$|[\\s,;])`, 'g')
    body = body.replace(wordBoundary, (_m, lead: string) => `${lead}\${${varName}}`)
  }

  const keyframeDecls = [...keyframeVars.entries()]
    .map(([original, varName]) => {
      const block = keyframeBlocks.find((b) => b.params.trim() === original)!
      return `const ${varName} = keyframes\`\n${indentBlock(dedent(escapeTemplateLiteral(block.body.trim())), '  ')}\n\``
    })
    .join('\n\n')

  /* The root element's own class is now expressed as `&`, so drop it from
   * the markup. Other elements keep theirs — the nested rules target them. */
  if (root && rootClass) {
    const remaining = rootClasses.slice(1)
    if (remaining.length) {
      root.attrs = root.attrs.map((a) =>
        a.name.toLowerCase() === 'class' ? { name: 'class', value: remaining.join(' ') } : a,
      )
    } else {
      removeAttr(root, 'class')
    }
  }

  if (!root) {
    notes.push(
      'This effect has more than one top-level element, so the styles are nested under a wrapping <div>. That extra element is inert (display: contents is not applied) — remove it if it disturbs your layout.',
    )
  }

  const inner = root
    ? renderMarkup(root.children, { jsx: true, indent: '      ', reactUncontrolled: true })
    : renderMarkup(roots, { jsx: true, indent: '      ', reactUncontrolled: true })

  const rootAttrs = root
    ? root.attrs
        .map((a) => {
          const name = a.name.toLowerCase() === 'for' ? 'htmlFor' : a.name.toLowerCase()
          return a.value === null ? ` ${name}` : ` ${name}="${a.value}"`
        })
        .join('')
    : ''

  const imports = keyframeVars.size
    ? "import styled, { keyframes } from 'styled-components'"
    : "import styled from 'styled-components'"

  const code = `/**
 * ${componentName} — ${input.name}
 * ${input.description}
 *
 * ${provenanceOf(input)}
 * Requires styled-components v5 or later.
 */
${imports}
${keyframeDecls ? '\n' + keyframeDecls + '\n' : ''}${globalBlocks ? '\n/* These at-rules must stay global — add them via createGlobalStyle. */\n' + globalBlocks.split('\n').map((l) => (l ? '// ' + l : '//')).join('\n') + '\n' : ''}
const ${componentName}Root = styled.${tag}\`
${indentBlock(body, '  ')}
\`

export function ${componentName}() {
  return (
    <${componentName}Root${rootAttrs}>
${inner}
    </${componentName}Root>
  )
}

export default ${componentName}
`

  if (keyframeVars.size) {
    notes.push(
      'Keyframes are hoisted into styled-components `keyframes` helpers, so their names are scoped to this component and cannot collide with animations elsewhere in your app.',
    )
  }
  notes.push(
    'The root class selector is rewritten to `&`, so the styles are bound to the component rather than to a global class name.',
  )

  return { code, notes }
}

/* ------------------------------------------------------------------ *
 *  Plain HTML / CSS
 * ------------------------------------------------------------------ */

export function buildStandaloneHtml(input: FrameworkInput): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${input.name} — Hoverlab</title>
  <style>
${indentBlock(input.css.trim(), '    ')}
  </style>
</head>
<body>
${renderMarkup(parseHtml(input.html), { indent: '  ' })}
</body>
</html>
`
}

/**
 * Class names an effect relies on — useful for the CLI, which warns when
 * pasted markup would collide with classes already in the target project.
 */
export function effectClassNames(html: string, css: string): string[] {
  const found = new Set<string>()
  for (const el of walkElements(parseHtml(html))) {
    for (const c of classList(el as HtmlElement)) found.add(c)
  }
  for (const rule of parseCss(css).rules) {
    for (const selector of rule.selectors) {
      for (const part of splitSelectorList(selector)) {
        for (const m of part.matchAll(/\.([-\w]+)/g)) found.add(m[1])
      }
    }
  }
  return [...found].sort()
}
