'use client'

/* GENERATED by scripts/build-block-playground.mjs — do not edit.
 *
 * block id -> the component TYPE, lazily imported, for the props
 * playground on /block/[slug]. See the generator for why this map exists
 * alongside registry.tsx rather than replacing it: that one holds elements
 * and must keep holding elements, this one holds types and is read by
 * exactly one component.
 *
 * `ssr: false` because the panel only ever renders after a reader has
 * clicked to open it — there is no server pass worth paying for, and a
 * block that touches a browser API on mount would fail one.
 */

import dynamic from 'next/dynamic'
import type * as React from 'react'

/**
 * Props are `Record<string, unknown>` rather than each block's own
 * interface: the playground builds its values from the props table, which
 * is parsed out of source text and typed as strings. The component still
 * checks them at runtime the way it always did, and the panel only ever
 * sends props it read off that block's own signature.
 */
export const PLAYGROUND_BLOCKS: Record<
  string,
  React.ComponentType<Record<string, unknown>>
> = {
  'activity-heatmap': dynamic(() => import('./sources/activity-heatmap').then((m) => m.ActivityHeatmap), {
    ssr: false,
    loading: () => null,
  }),
  'activity-timeline': dynamic(() => import('./sources/activity-timeline').then((m) => m.ActivityTimeline), {
    ssr: false,
    loading: () => null,
  }),
  'agent-cost-breakdown': dynamic(() => import('./sources/agent-cost-breakdown').then((m) => m.AgentCostBreakdown), {
    ssr: false,
    loading: () => null,
  }),
  'agent-diff-review': dynamic(() => import('./sources/agent-diff-review').then((m) => m.AgentDiffReview), {
    ssr: false,
    loading: () => null,
  }),
  'agent-retry-log': dynamic(() => import('./sources/agent-retry-log').then((m) => m.AgentRetryLog), {
    ssr: false,
    loading: () => null,
  }),
  'agent-run-failure': dynamic(() => import('./sources/agent-run-failure').then((m) => m.AgentRunFailure), {
    ssr: false,
    loading: () => null,
  }),
  'agent-task-list': dynamic(() => import('./sources/agent-task-list').then((m) => m.AgentTaskList), {
    ssr: false,
    loading: () => null,
  }),
  'agent-thinking-trace': dynamic(() => import('./sources/agent-thinking-trace').then((m) => m.AgentThinkingTrace), {
    ssr: false,
    loading: () => null,
  }),
  'agent-tool-calls': dynamic(() => import('./sources/agent-tool-calls').then((m) => m.AgentToolCalls), {
    ssr: false,
    loading: () => null,
  }),
  'agent-working-indicator': dynamic(() => import('./sources/agent-working-indicator').then((m) => m.AgentWorkingIndicator), {
    ssr: false,
    loading: () => null,
  }),
  'ai-action-menu': dynamic(() => import('./sources/ai-action-menu').then((m) => m.AiActionMenu), {
    ssr: false,
    loading: () => null,
  }),
  'ai-inline-suggestion': dynamic(() => import('./sources/ai-inline-suggestion').then((m) => m.AiInlineSuggestion), {
    ssr: false,
    loading: () => null,
  }),
  'ai-insight-cards': dynamic(() => import('./sources/ai-insight-cards').then((m) => m.AiInsightCards), {
    ssr: false,
    loading: () => null,
  }),
  'ai-inspector-panel': dynamic(() => import('./sources/ai-inspector-panel').then((m) => m.AiInspectorPanel), {
    ssr: false,
    loading: () => null,
  }),
  'ai-slash-menu': dynamic(() => import('./sources/ai-slash-menu').then((m) => m.AiSlashMenu), {
    ssr: false,
    loading: () => null,
  }),
  'announcement-bar': dynamic(() => import('./sources/announcement-bar').then((m) => m.AnnouncementBar), {
    ssr: false,
    loading: () => null,
  }),
  'api-endpoint-card': dynamic(() => import('./sources/api-endpoint-card').then((m) => m.ApiEndpointCard), {
    ssr: false,
    loading: () => null,
  }),
  'applied-filters-bar': dynamic(() => import('./sources/applied-filters-bar').then((m) => m.AppliedFiltersBar), {
    ssr: false,
    loading: () => null,
  }),
  'approval-policy-list': dynamic(() => import('./sources/approval-policy-list').then((m) => m.ApprovalPolicyList), {
    ssr: false,
    loading: () => null,
  }),
  'approval-queue': dynamic(() => import('./sources/approval-queue').then((m) => m.ApprovalQueue), {
    ssr: false,
    loading: () => null,
  }),
  'approval-request-card': dynamic(() => import('./sources/approval-request-card').then((m) => m.ApprovalRequestCard), {
    ssr: false,
    loading: () => null,
  }),
  'article-header': dynamic(() => import('./sources/article-header').then((m) => m.ArticleHeader), {
    ssr: false,
    loading: () => null,
  }),
  'auth-forgot-password': dynamic(() => import('./sources/auth-forgot-password').then((m) => m.AuthForgotPassword), {
    ssr: false,
    loading: () => null,
  }),
  'auth-login-card': dynamic(() => import('./sources/auth-login-card').then((m) => m.AuthLoginCard), {
    ssr: false,
    loading: () => null,
  }),
  'auth-magic-link-form': dynamic(() => import('./sources/auth-magic-link-form').then((m) => m.AuthMagicLinkForm), {
    ssr: false,
    loading: () => null,
  }),
  'auth-otp-verify': dynamic(() => import('./sources/auth-otp-verify').then((m) => m.AuthOtpVerify), {
    ssr: false,
    loading: () => null,
  }),
  'auth-reset-password': dynamic(() => import('./sources/auth-reset-password').then((m) => m.AuthResetPassword), {
    ssr: false,
    loading: () => null,
  }),
  'auth-signup-split': dynamic(() => import('./sources/auth-signup-split').then((m) => m.AuthSignupSplit), {
    ssr: false,
    loading: () => null,
  }),
  'auth-sso-domain': dynamic(() => import('./sources/auth-sso-domain').then((m) => m.AuthSsoDomain), {
    ssr: false,
    loading: () => null,
  }),
  'auth-two-factor': dynamic(() => import('./sources/auth-two-factor').then((m) => m.AuthTwoFactor), {
    ssr: false,
    loading: () => null,
  }),
  'avatar-crop-upload': dynamic(() => import('./sources/avatar-crop-upload').then((m) => m.AvatarCropUpload), {
    ssr: false,
    loading: () => null,
  }),
  'back-in-stock-form': dynamic(() => import('./sources/back-in-stock-form').then((m) => m.BackInStockForm), {
    ssr: false,
    loading: () => null,
  }),
  'bar-chart-panel': dynamic(() => import('./sources/bar-chart-panel').then((m) => m.BarChartPanel), {
    ssr: false,
    loading: () => null,
  }),
  'bento-features': dynamic(() => import('./sources/bento-features').then((m) => m.BentoFeatures), {
    ssr: false,
    loading: () => null,
  }),
  'billing-credit-balance': dynamic(() => import('./sources/billing-credit-balance').then((m) => m.BillingCreditBalance), {
    ssr: false,
    loading: () => null,
  }),
  'billing-invoice-detail': dynamic(() => import('./sources/billing-invoice-detail').then((m) => m.BillingInvoiceDetail), {
    ssr: false,
    loading: () => null,
  }),
  'billing-plan-summary': dynamic(() => import('./sources/billing-plan-summary').then((m) => m.BillingPlanSummary), {
    ssr: false,
    loading: () => null,
  }),
  'billing-seat-manager': dynamic(() => import('./sources/billing-seat-manager').then((m) => m.BillingSeatManager), {
    ssr: false,
    loading: () => null,
  }),
  'blog-post-grid': dynamic(() => import('./sources/blog-post-grid').then((m) => m.BlogPostGrid), {
    ssr: false,
    loading: () => null,
  }),
  'booking-scheduler': dynamic(() => import('./sources/booking-scheduler').then((m) => m.BookingScheduler), {
    ssr: false,
    loading: () => null,
  }),
  'bottom-sheet-mobile': dynamic(() => import('./sources/bottom-sheet-mobile').then((m) => m.BottomSheetMobile), {
    ssr: false,
    loading: () => null,
  }),
  'calendar-month': dynamic(() => import('./sources/calendar-month').then((m) => m.CalendarMonth), {
    ssr: false,
    loading: () => null,
  }),
  'call-device-settings': dynamic(() => import('./sources/call-device-settings').then((m) => m.CallDeviceSettings), {
    ssr: false,
    loading: () => null,
  }),
  'cart-drawer': dynamic(() => import('./sources/cart-drawer').then((m) => m.CartDrawer), {
    ssr: false,
    loading: () => null,
  }),
  'cart-line-items': dynamic(() => import('./sources/cart-line-items').then((m) => m.CartLineItems), {
    ssr: false,
    loading: () => null,
  }),
  'case-study-grid': dynamic(() => import('./sources/case-study-grid').then((m) => m.CaseStudyGrid), {
    ssr: false,
    loading: () => null,
  }),
  'changelog-timeline': dynamic(() => import('./sources/changelog-timeline').then((m) => m.ChangelogTimeline), {
    ssr: false,
    loading: () => null,
  }),
  'chat-artifact-canvas': dynamic(() => import('./sources/chat-artifact-canvas').then((m) => m.ChatArtifactCanvas), {
    ssr: false,
    loading: () => null,
  }),
  'chat-attachment-tray': dynamic(() => import('./sources/chat-attachment-tray').then((m) => m.ChatAttachmentTray), {
    ssr: false,
    loading: () => null,
  }),
  'chat-empty-state': dynamic(() => import('./sources/chat-empty-state').then((m) => m.ChatEmptyState), {
    ssr: false,
    loading: () => null,
  }),
  'chat-message-branches': dynamic(() => import('./sources/chat-message-branches').then((m) => m.ChatMessageBranches), {
    ssr: false,
    loading: () => null,
  }),
  'chat-model-picker': dynamic(() => import('./sources/chat-model-picker').then((m) => m.ChatModelPicker), {
    ssr: false,
    loading: () => null,
  }),
  'chat-prompt-bar': dynamic(() => import('./sources/chat-prompt-bar').then((m) => m.ChatPromptBar), {
    ssr: false,
    loading: () => null,
  }),
  'chat-streaming-answer': dynamic(() => import('./sources/chat-streaming-answer').then((m) => m.ChatStreamingAnswer), {
    ssr: false,
    loading: () => null,
  }),
  'chat-thread-panel': dynamic(() => import('./sources/chat-thread-panel').then((m) => m.ChatThreadPanel), {
    ssr: false,
    loading: () => null,
  }),
  'checkout-express-payment': dynamic(() => import('./sources/checkout-express-payment').then((m) => m.CheckoutExpressPayment), {
    ssr: false,
    loading: () => null,
  }),
  'checkout-form': dynamic(() => import('./sources/checkout-form').then((m) => m.CheckoutForm), {
    ssr: false,
    loading: () => null,
  }),
  'code-showcase': dynamic(() => import('./sources/code-showcase').then((m) => m.CodeShowcase), {
    ssr: false,
    loading: () => null,
  }),
  'code-tabs-panel': dynamic(() => import('./sources/code-tabs-panel').then((m) => m.CodeTabsPanel), {
    ssr: false,
    loading: () => null,
  }),
  'collection-story-split': dynamic(() => import('./sources/collection-story-split').then((m) => m.CollectionStorySplit), {
    ssr: false,
    loading: () => null,
  }),
  'collection-toolbar': dynamic(() => import('./sources/collection-toolbar').then((m) => m.CollectionToolbar), {
    ssr: false,
    loading: () => null,
  }),
  'command-palette': dynamic(() => import('./sources/command-palette').then((m) => m.CommandPalette), {
    ssr: false,
    loading: () => null,
  }),
  'community-band': dynamic(() => import('./sources/community-band').then((m) => m.CommunityBand), {
    ssr: false,
    loading: () => null,
  }),
  'comparison-table': dynamic(() => import('./sources/comparison-table').then((m) => m.ComparisonTable), {
    ssr: false,
    loading: () => null,
  }),
  'confidence-recommendation': dynamic(() => import('./sources/confidence-recommendation').then((m) => m.ConfidenceRecommendation), {
    ssr: false,
    loading: () => null,
  }),
  'confirm-dialog': dynamic(() => import('./sources/confirm-dialog').then((m) => m.ConfirmDialog), {
    ssr: false,
    loading: () => null,
  }),
  'contact-form-split': dynamic(() => import('./sources/contact-form-split').then((m) => m.ContactFormSplit), {
    ssr: false,
    loading: () => null,
  }),
  'contact-sales-form': dynamic(() => import('./sources/contact-sales-form').then((m) => m.ContactSalesForm), {
    ssr: false,
    loading: () => null,
  }),
  'context-chunk-cards': dynamic(() => import('./sources/context-chunk-cards').then((m) => m.ContextChunkCards), {
    ssr: false,
    loading: () => null,
  }),
  'context-scope-list': dynamic(() => import('./sources/context-scope-list').then((m) => m.ContextScopeList), {
    ssr: false,
    loading: () => null,
  }),
  'context-window-budget': dynamic(() => import('./sources/context-window-budget').then((m) => m.ContextWindowBudget), {
    ssr: false,
    loading: () => null,
  }),
  'cookie-consent': dynamic(() => import('./sources/cookie-consent').then((m) => m.CookieConsent), {
    ssr: false,
    loading: () => null,
  }),
  'crud-archive-restore': dynamic(() => import('./sources/crud-archive-restore').then((m) => m.CrudArchiveRestore), {
    ssr: false,
    loading: () => null,
  }),
  'crud-bulk-edit-drawer': dynamic(() => import('./sources/crud-bulk-edit-drawer').then((m) => m.CrudBulkEditDrawer), {
    ssr: false,
    loading: () => null,
  }),
  'crud-create-drawer': dynamic(() => import('./sources/crud-create-drawer').then((m) => m.CrudCreateDrawer), {
    ssr: false,
    loading: () => null,
  }),
  'crud-create-form': dynamic(() => import('./sources/crud-create-form').then((m) => m.CrudCreateForm), {
    ssr: false,
    loading: () => null,
  }),
  'crud-create-modal': dynamic(() => import('./sources/crud-create-modal').then((m) => m.CrudCreateModal), {
    ssr: false,
    loading: () => null,
  }),
  'crud-delete-cascade': dynamic(() => import('./sources/crud-delete-cascade').then((m) => m.CrudDeleteCascade), {
    ssr: false,
    loading: () => null,
  }),
  'crud-read-modal': dynamic(() => import('./sources/crud-read-modal').then((m) => m.CrudReadModal), {
    ssr: false,
    loading: () => null,
  }),
  'crud-read-page': dynamic(() => import('./sources/crud-read-page').then((m) => m.CrudReadPage), {
    ssr: false,
    loading: () => null,
  }),
  'crud-success-state': dynamic(() => import('./sources/crud-success-state').then((m) => m.CrudSuccessState), {
    ssr: false,
    loading: () => null,
  }),
  'crud-update-drawer': dynamic(() => import('./sources/crud-update-drawer').then((m) => m.CrudUpdateDrawer), {
    ssr: false,
    loading: () => null,
  }),
  'crud-update-form': dynamic(() => import('./sources/crud-update-form').then((m) => m.CrudUpdateForm), {
    ssr: false,
    loading: () => null,
  }),
  'crud-update-modal': dynamic(() => import('./sources/crud-update-modal').then((m) => m.CrudUpdateModal), {
    ssr: false,
    loading: () => null,
  }),
  'csv-import-mapper': dynamic(() => import('./sources/csv-import-mapper').then((m) => m.CsvImportMapper), {
    ssr: false,
    loading: () => null,
  }),
  'cta-inline-card': dynamic(() => import('./sources/cta-inline-card').then((m) => m.CtaInlineCard), {
    ssr: false,
    loading: () => null,
  }),
  'cta-split-panel': dynamic(() => import('./sources/cta-split-panel').then((m) => m.CtaSplitPanel), {
    ssr: false,
    loading: () => null,
  }),
  'cta-sticky-bar': dynamic(() => import('./sources/cta-sticky-bar').then((m) => m.CtaStickyBar), {
    ssr: false,
    loading: () => null,
  }),
  'customer-outcome-band': dynamic(() => import('./sources/customer-outcome-band').then((m) => m.CustomerOutcomeBand), {
    ssr: false,
    loading: () => null,
  }),
  'dashboard-activity-feed': dynamic(() => import('./sources/dashboard-activity-feed').then((m) => m.DashboardActivityFeed), {
    ssr: false,
    loading: () => null,
  }),
  'dashboard-alert-rules': dynamic(() => import('./sources/dashboard-alert-rules').then((m) => m.DashboardAlertRules), {
    ssr: false,
    loading: () => null,
  }),
  'dashboard-comparison-period': dynamic(() => import('./sources/dashboard-comparison-period').then((m) => m.DashboardComparisonPeriod), {
    ssr: false,
    loading: () => null,
  }),
  'dashboard-page-header': dynamic(() => import('./sources/dashboard-page-header').then((m) => m.DashboardPageHeader), {
    ssr: false,
    loading: () => null,
  }),
  'dashboard-saved-views': dynamic(() => import('./sources/dashboard-saved-views').then((m) => m.DashboardSavedViews), {
    ssr: false,
    loading: () => null,
  }),
  'dashboard-shell': dynamic(() => import('./sources/dashboard-shell').then((m) => m.DashboardShell), {
    ssr: false,
    loading: () => null,
  }),
  'dashboard-stat-cards': dynamic(() => import('./sources/dashboard-stat-cards').then((m) => m.DashboardStatCards), {
    ssr: false,
    loading: () => null,
  }),
  'data-migration-split': dynamic(() => import('./sources/data-migration-split').then((m) => m.DataMigrationSplit), {
    ssr: false,
    loading: () => null,
  }),
  'data-table-bulk-actions': dynamic(() => import('./sources/data-table-bulk-actions').then((m) => m.DataTableBulkActions), {
    ssr: false,
    loading: () => null,
  }),
  'data-table-column-manager': dynamic(() => import('./sources/data-table-column-manager').then((m) => m.DataTableColumnManager), {
    ssr: false,
    loading: () => null,
  }),
  'data-table-expandable': dynamic(() => import('./sources/data-table-expandable').then((m) => m.DataTableExpandable), {
    ssr: false,
    loading: () => null,
  }),
  'data-table-grouped-rows': dynamic(() => import('./sources/data-table-grouped-rows').then((m) => m.DataTableGroupedRows), {
    ssr: false,
    loading: () => null,
  }),
  'data-table-inline-edit': dynamic(() => import('./sources/data-table-inline-edit').then((m) => m.DataTableInlineEdit), {
    ssr: false,
    loading: () => null,
  }),
  'data-table-pagination': dynamic(() => import('./sources/data-table-pagination').then((m) => m.DataTablePagination), {
    ssr: false,
    loading: () => null,
  }),
  'data-table-sortable': dynamic(() => import('./sources/data-table-sortable').then((m) => m.DataTableSortable), {
    ssr: false,
    loading: () => null,
  }),
  'data-table-toolbar': dynamic(() => import('./sources/data-table-toolbar').then((m) => m.DataTableToolbar), {
    ssr: false,
    loading: () => null,
  }),
  'demo-request-form': dynamic(() => import('./sources/demo-request-form').then((m) => m.DemoRequestForm), {
    ssr: false,
    loading: () => null,
  }),
  'digest-schedule-form': dynamic(() => import('./sources/digest-schedule-form').then((m) => m.DigestScheduleForm), {
    ssr: false,
    loading: () => null,
  }),
  'discount-modal': dynamic(() => import('./sources/discount-modal').then((m) => m.DiscountModal), {
    ssr: false,
    loading: () => null,
  }),
  'docs-layout': dynamic(() => import('./sources/docs-layout').then((m) => m.DocsLayout), {
    ssr: false,
    loading: () => null,
  }),
  'donut-breakdown': dynamic(() => import('./sources/donut-breakdown').then((m) => m.DonutBreakdown), {
    ssr: false,
    loading: () => null,
  }),
  'drawer-record-detail': dynamic(() => import('./sources/drawer-record-detail').then((m) => m.DrawerRecordDetail), {
    ssr: false,
    loading: () => null,
  }),
  'email-newsletter-digest': dynamic(() => import('./sources/email-newsletter-digest').then((m) => m.EmailNewsletterDigest), {
    ssr: false,
    loading: () => null,
  }),
  'email-product-announcement': dynamic(() => import('./sources/email-product-announcement').then((m) => m.EmailProductAnnouncement), {
    ssr: false,
    loading: () => null,
  }),
  'email-promo-offer': dynamic(() => import('./sources/email-promo-offer').then((m) => m.EmailPromoOffer), {
    ssr: false,
    loading: () => null,
  }),
  'email-winback': dynamic(() => import('./sources/email-winback').then((m) => m.EmailWinback), {
    ssr: false,
    loading: () => null,
  }),
  'empty-filtered-results': dynamic(() => import('./sources/empty-filtered-results').then((m) => m.EmptyFilteredResults), {
    ssr: false,
    loading: () => null,
  }),
  'empty-state-cta': dynamic(() => import('./sources/empty-state-cta').then((m) => m.EmptyState), {
    ssr: false,
    loading: () => null,
  }),
  'error-state-retry': dynamic(() => import('./sources/error-state-retry').then((m) => m.ErrorStateRetry), {
    ssr: false,
    loading: () => null,
  }),
  'escalation-queue-list': dynamic(() => import('./sources/escalation-queue-list').then((m) => m.EscalationQueueList), {
    ssr: false,
    loading: () => null,
  }),
  'event-agenda-grid': dynamic(() => import('./sources/event-agenda-grid').then((m) => m.EventAgendaGrid), {
    ssr: false,
    loading: () => null,
  }),
  'faq-accordion': dynamic(() => import('./sources/faq-accordion').then((m) => m.FaqAccordion), {
    ssr: false,
    loading: () => null,
  }),
  'faq-categorized': dynamic(() => import('./sources/faq-categorized').then((m) => m.FaqCategorized), {
    ssr: false,
    loading: () => null,
  }),
  'faq-grid': dynamic(() => import('./sources/faq-grid').then((m) => m.FaqGrid), {
    ssr: false,
    loading: () => null,
  }),
  'faq-objection-list': dynamic(() => import('./sources/faq-objection-list').then((m) => m.FaqObjectionList), {
    ssr: false,
    loading: () => null,
  }),
  'faq-search': dynamic(() => import('./sources/faq-search').then((m) => m.FaqSearch), {
    ssr: false,
    loading: () => null,
  }),
  'faq-two-column': dynamic(() => import('./sources/faq-two-column').then((m) => m.FaqTwoColumn), {
    ssr: false,
    loading: () => null,
  }),
  'feature-icon-grid': dynamic(() => import('./sources/feature-icon-grid').then((m) => m.FeatureIconGrid), {
    ssr: false,
    loading: () => null,
  }),
  'feature-rows': dynamic(() => import('./sources/feature-rows').then((m) => m.FeatureRows), {
    ssr: false,
    loading: () => null,
  }),
  'feature-tabs': dynamic(() => import('./sources/feature-tabs').then((m) => m.FeatureTabs), {
    ssr: false,
    loading: () => null,
  }),
  'feedback-widget': dynamic(() => import('./sources/feedback-widget').then((m) => m.FeedbackWidget), {
    ssr: false,
    loading: () => null,
  }),
  'file-dropzone': dynamic(() => import('./sources/file-dropzone').then((m) => m.FileDropzone), {
    ssr: false,
    loading: () => null,
  }),
  'filter-drawer-facets': dynamic(() => import('./sources/filter-drawer-facets').then((m) => m.FilterDrawerFacets), {
    ssr: false,
    loading: () => null,
  }),
  'footer-compliance': dynamic(() => import('./sources/footer-compliance').then((m) => m.FooterCompliance), {
    ssr: false,
    loading: () => null,
  }),
  'footer-mega': dynamic(() => import('./sources/footer-mega').then((m) => m.FooterMega), {
    ssr: false,
    loading: () => null,
  }),
  'footer-minimal': dynamic(() => import('./sources/footer-minimal').then((m) => m.FooterMinimal), {
    ssr: false,
    loading: () => null,
  }),
  'footer-newsletter': dynamic(() => import('./sources/footer-newsletter').then((m) => m.FooterNewsletter), {
    ssr: false,
    loading: () => null,
  }),
  'footer-status-locale': dynamic(() => import('./sources/footer-status-locale').then((m) => m.FooterStatusLocale), {
    ssr: false,
    loading: () => null,
  }),
  'form-error-summary': dynamic(() => import('./sources/form-error-summary').then((m) => m.FormErrorSummary), {
    ssr: false,
    loading: () => null,
  }),
  'funnel-conversion-panel': dynamic(() => import('./sources/funnel-conversion-panel').then((m) => m.FunnelConversionPanel), {
    ssr: false,
    loading: () => null,
  }),
  'gift-card-balance': dynamic(() => import('./sources/gift-card-balance').then((m) => m.GiftCardBalance), {
    ssr: false,
    loading: () => null,
  }),
  'gift-card-purchase': dynamic(() => import('./sources/gift-card-purchase').then((m) => m.GiftCardPurchase), {
    ssr: false,
    loading: () => null,
  }),
  'gift-options-form': dynamic(() => import('./sources/gift-options-form').then((m) => m.GiftOptionsForm), {
    ssr: false,
    loading: () => null,
  }),
  'grounding-split': dynamic(() => import('./sources/grounding-split').then((m) => m.GroundingSplit), {
    ssr: false,
    loading: () => null,
  }),
  'guest-checkout-form': dynamic(() => import('./sources/guest-checkout-form').then((m) => m.GuestCheckoutForm), {
    ssr: false,
    loading: () => null,
  }),
  'hero-app-download': dynamic(() => import('./sources/hero-app-download').then((m) => m.HeroAppDownload), {
    ssr: false,
    loading: () => null,
  }),
  'hero-booking': dynamic(() => import('./sources/hero-booking').then((m) => m.HeroBooking), {
    ssr: false,
    loading: () => null,
  }),
  'hero-centered': dynamic(() => import('./sources/hero-centered').then((m) => m.HeroCentered), {
    ssr: false,
    loading: () => null,
  }),
  'hero-editorial': dynamic(() => import('./sources/hero-editorial').then((m) => m.HeroEditorial), {
    ssr: false,
    loading: () => null,
  }),
  'hero-integrations': dynamic(() => import('./sources/hero-integrations').then((m) => m.HeroIntegrations), {
    ssr: false,
    loading: () => null,
  }),
  'hero-media-overlay': dynamic(() => import('./sources/hero-media-overlay').then((m) => m.HeroMediaOverlay), {
    ssr: false,
    loading: () => null,
  }),
  'hero-metrics': dynamic(() => import('./sources/hero-metrics').then((m) => m.HeroMetrics), {
    ssr: false,
    loading: () => null,
  }),
  'hero-price-anchor': dynamic(() => import('./sources/hero-price-anchor').then((m) => m.HeroPriceAnchor), {
    ssr: false,
    loading: () => null,
  }),
  'hero-screenshot': dynamic(() => import('./sources/hero-screenshot').then((m) => m.HeroScreenshot), {
    ssr: false,
    loading: () => null,
  }),
  'hero-search': dynamic(() => import('./sources/hero-search').then((m) => m.HeroSearch), {
    ssr: false,
    loading: () => null,
  }),
  'hero-split': dynamic(() => import('./sources/hero-split').then((m) => m.HeroSplit), {
    ssr: false,
    loading: () => null,
  }),
  'hero-terminal': dynamic(() => import('./sources/hero-terminal').then((m) => m.HeroTerminal), {
    ssr: false,
    loading: () => null,
  }),
  'hero-testimonial': dynamic(() => import('./sources/hero-testimonial').then((m) => m.HeroTestimonial), {
    ssr: false,
    loading: () => null,
  }),
  'hero-waitlist': dynamic(() => import('./sources/hero-waitlist').then((m) => m.HeroWaitlist), {
    ssr: false,
    loading: () => null,
  }),
  'human-oversight-split': dynamic(() => import('./sources/human-oversight-split').then((m) => m.HumanOversightSplit), {
    ssr: false,
    loading: () => null,
  }),
  'import-from-url-form': dynamic(() => import('./sources/import-from-url-form').then((m) => m.ImportFromUrlForm), {
    ssr: false,
    loading: () => null,
  }),
  'inbox-thread-detail': dynamic(() => import('./sources/inbox-thread-detail').then((m) => m.InboxThreadDetail), {
    ssr: false,
    loading: () => null,
  }),
  'inbox-thread-list': dynamic(() => import('./sources/inbox-thread-list').then((m) => m.InboxThreadList), {
    ssr: false,
    loading: () => null,
  }),
  'integration-depth-split': dynamic(() => import('./sources/integration-depth-split').then((m) => m.IntegrationDepthSplit), {
    ssr: false,
    loading: () => null,
  }),
  'integration-grid': dynamic(() => import('./sources/integration-grid').then((m) => m.IntegrationGrid), {
    ssr: false,
    loading: () => null,
  }),
  'invoice-history-table': dynamic(() => import('./sources/invoice-history-table').then((m) => m.InvoiceHistoryTable), {
    ssr: false,
    loading: () => null,
  }),
  'job-listing-board': dynamic(() => import('./sources/job-listing-board').then((m) => m.JobListingBoard), {
    ssr: false,
    loading: () => null,
  }),
  'kanban-board': dynamic(() => import('./sources/kanban-board').then((m) => m.KanbanBoard), {
    ssr: false,
    loading: () => null,
  }),
  'keyboard-shortcuts-sheet': dynamic(() => import('./sources/keyboard-shortcuts-sheet').then((m) => m.KeyboardShortcutsSheet), {
    ssr: false,
    loading: () => null,
  }),
  'knowledge-source-picker': dynamic(() => import('./sources/knowledge-source-picker').then((m) => m.KnowledgeSourcePicker), {
    ssr: false,
    loading: () => null,
  }),
  'kpi-summary-band': dynamic(() => import('./sources/kpi-summary-band').then((m) => m.KpiSummaryBand), {
    ssr: false,
    loading: () => null,
  }),
  'line-chart-panel': dynamic(() => import('./sources/line-chart-panel').then((m) => m.LineChartPanel), {
    ssr: false,
    loading: () => null,
  }),
  'listing-map-split': dynamic(() => import('./sources/listing-map-split').then((m) => m.ListingMapSplit), {
    ssr: false,
    loading: () => null,
  }),
  'logo-cloud': dynamic(() => import('./sources/logo-cloud').then((m) => m.LogoCloud), {
    ssr: false,
    loading: () => null,
  }),
  'logo-grid': dynamic(() => import('./sources/logo-grid').then((m) => m.LogoGrid), {
    ssr: false,
    loading: () => null,
  }),
  'logo-segments': dynamic(() => import('./sources/logo-segments').then((m) => m.LogoSegments), {
    ssr: false,
    loading: () => null,
  }),
  'logo-strip': dynamic(() => import('./sources/logo-strip').then((m) => m.LogoStrip), {
    ssr: false,
    loading: () => null,
  }),
  'maintenance-window-state': dynamic(() => import('./sources/maintenance-window-state').then((m) => m.MaintenanceWindowState), {
    ssr: false,
    loading: () => null,
  }),
  'menu-course-list': dynamic(() => import('./sources/menu-course-list').then((m) => m.MenuCourseList), {
    ssr: false,
    loading: () => null,
  }),
  'message-attachment-bubble': dynamic(() => import('./sources/message-attachment-bubble').then((m) => m.MessageAttachmentBubble), {
    ssr: false,
    loading: () => null,
  }),
  'message-bubble-thread': dynamic(() => import('./sources/message-bubble-thread').then((m) => m.MessageBubbleThread), {
    ssr: false,
    loading: () => null,
  }),
  'metric-alert-list': dynamic(() => import('./sources/metric-alert-list').then((m) => m.MetricAlertList), {
    ssr: false,
    loading: () => null,
  }),
  'metric-sparkline-cards': dynamic(() => import('./sources/metric-sparkline-cards').then((m) => m.MetricSparklineCards), {
    ssr: false,
    loading: () => null,
  }),
  'modal-unsaved-changes': dynamic(() => import('./sources/modal-unsaved-changes').then((m) => m.ModalUnsavedChanges), {
    ssr: false,
    loading: () => null,
  }),
  'multi-step-form': dynamic(() => import('./sources/multi-step-form').then((m) => m.MultiStepForm), {
    ssr: false,
    loading: () => null,
  }),
  'nav-mobile-drawer': dynamic(() => import('./sources/nav-mobile-drawer').then((m) => m.NavMobileDrawer), {
    ssr: false,
    loading: () => null,
  }),
  'navbar-authenticated': dynamic(() => import('./sources/navbar-authenticated').then((m) => m.NavbarAuthenticated), {
    ssr: false,
    loading: () => null,
  }),
  'navbar-mega-menu': dynamic(() => import('./sources/navbar-mega-menu').then((m) => m.NavbarMegaMenu), {
    ssr: false,
    loading: () => null,
  }),
  'navbar-simple': dynamic(() => import('./sources/navbar-simple').then((m) => m.NavbarSimple), {
    ssr: false,
    loading: () => null,
  }),
  'newsletter-signup': dynamic(() => import('./sources/newsletter-signup').then((m) => m.NewsletterSignup), {
    ssr: false,
    loading: () => null,
  }),
  'not-found-404': dynamic(() => import('./sources/not-found-404').then((m) => m.NotFound404), {
    ssr: false,
    loading: () => null,
  }),
  'notification-channel-list': dynamic(() => import('./sources/notification-channel-list').then((m) => m.NotificationChannelList), {
    ssr: false,
    loading: () => null,
  }),
  'notification-digest-list': dynamic(() => import('./sources/notification-digest-list').then((m) => m.NotificationDigestList), {
    ssr: false,
    loading: () => null,
  }),
  'notification-inbox': dynamic(() => import('./sources/notification-inbox').then((m) => m.NotificationInbox), {
    ssr: false,
    loading: () => null,
  }),
  'notification-preferences': dynamic(() => import('./sources/notification-preferences').then((m) => m.NotificationPreferences), {
    ssr: false,
    loading: () => null,
  }),
  'offline-state-banner': dynamic(() => import('./sources/offline-state-banner').then((m) => m.OfflineStateBanner), {
    ssr: false,
    loading: () => null,
  }),
  'onboarding-checklist': dynamic(() => import('./sources/onboarding-checklist').then((m) => m.OnboardingChecklist), {
    ssr: false,
    loading: () => null,
  }),
  'onboarding-import-data': dynamic(() => import('./sources/onboarding-import-data').then((m) => m.OnboardingImportData), {
    ssr: false,
    loading: () => null,
  }),
  'onboarding-role-picker': dynamic(() => import('./sources/onboarding-role-picker').then((m) => m.OnboardingRolePicker), {
    ssr: false,
    loading: () => null,
  }),
  'order-confirmation': dynamic(() => import('./sources/order-confirmation').then((m) => m.OrderConfirmation), {
    ssr: false,
    loading: () => null,
  }),
  'order-history-list': dynamic(() => import('./sources/order-history-list').then((m) => m.OrderHistoryList), {
    ssr: false,
    loading: () => null,
  }),
  'order-lookup-form': dynamic(() => import('./sources/order-lookup-form').then((m) => m.OrderLookupForm), {
    ssr: false,
    loading: () => null,
  }),
  'order-summary-panel': dynamic(() => import('./sources/order-summary-panel').then((m) => m.OrderSummaryPanel), {
    ssr: false,
    loading: () => null,
  }),
  'order-tracking-timeline': dynamic(() => import('./sources/order-tracking-timeline').then((m) => m.OrderTrackingTimeline), {
    ssr: false,
    loading: () => null,
  }),
  'payment-method-card': dynamic(() => import('./sources/payment-method-card').then((m) => m.PaymentMethodCard), {
    ssr: false,
    loading: () => null,
  }),
  'permission-denied-state': dynamic(() => import('./sources/permission-denied-state').then((m) => m.PermissionDeniedState), {
    ssr: false,
    loading: () => null,
  }),
  'permission-scope-dialog': dynamic(() => import('./sources/permission-scope-dialog').then((m) => m.PermissionScopeDialog), {
    ssr: false,
    loading: () => null,
  }),
  'persona-cards': dynamic(() => import('./sources/persona-cards').then((m) => m.PersonaCards), {
    ssr: false,
    loading: () => null,
  }),
  'plan-limits-list': dynamic(() => import('./sources/plan-limits-list').then((m) => m.PlanLimitsList), {
    ssr: false,
    loading: () => null,
  }),
  'price-ticker-strip': dynamic(() => import('./sources/price-ticker-strip').then((m) => m.PriceTickerStrip), {
    ssr: false,
    loading: () => null,
  }),
  'pricing-credits': dynamic(() => import('./sources/pricing-credits').then((m) => m.PricingCredits), {
    ssr: false,
    loading: () => null,
  }),
  'pricing-plan-picker': dynamic(() => import('./sources/pricing-plan-picker').then((m) => m.PricingPlanPicker), {
    ssr: false,
    loading: () => null,
  }),
  'pricing-single': dynamic(() => import('./sources/pricing-single').then((m) => m.PricingSingle), {
    ssr: false,
    loading: () => null,
  }),
  'pricing-tiers': dynamic(() => import('./sources/pricing-tiers').then((m) => m.PricingTiers), {
    ssr: false,
    loading: () => null,
  }),
  'pricing-usage-calculator': dynamic(() => import('./sources/pricing-usage-calculator').then((m) => m.PricingUsageCalculator), {
    ssr: false,
    loading: () => null,
  }),
  'pricing-value-split': dynamic(() => import('./sources/pricing-value-split').then((m) => m.PricingValueSplit), {
    ssr: false,
    loading: () => null,
  }),
  'product-buy-box': dynamic(() => import('./sources/product-buy-box').then((m) => m.ProductBuyBox), {
    ssr: false,
    loading: () => null,
  }),
  'product-compare-table': dynamic(() => import('./sources/product-compare-table').then((m) => m.ProductCompareTable), {
    ssr: false,
    loading: () => null,
  }),
  'product-filter-sidebar': dynamic(() => import('./sources/product-filter-sidebar').then((m) => m.ProductFilterSidebar), {
    ssr: false,
    loading: () => null,
  }),
  'product-gallery': dynamic(() => import('./sources/product-gallery').then((m) => m.ProductGallery), {
    ssr: false,
    loading: () => null,
  }),
  'product-grid': dynamic(() => import('./sources/product-grid').then((m) => m.ProductGrid), {
    ssr: false,
    loading: () => null,
  }),
  'product-info-accordion': dynamic(() => import('./sources/product-info-accordion').then((m) => m.ProductInfoAccordion), {
    ssr: false,
    loading: () => null,
  }),
  'product-rail': dynamic(() => import('./sources/product-rail').then((m) => m.ProductRail), {
    ssr: false,
    loading: () => null,
  }),
  'product-review-summary': dynamic(() => import('./sources/product-review-summary').then((m) => m.ProductReviewSummary), {
    ssr: false,
    loading: () => null,
  }),
  'product-size-guide': dynamic(() => import('./sources/product-size-guide').then((m) => m.ProductSizeGuide), {
    ssr: false,
    loading: () => null,
  }),
  'product-spec-split': dynamic(() => import('./sources/product-spec-split').then((m) => m.ProductSpecSplit), {
    ssr: false,
    loading: () => null,
  }),
  'product-tour-coachmark': dynamic(() => import('./sources/product-tour-coachmark').then((m) => m.ProductTourCoachmark), {
    ssr: false,
    loading: () => null,
  }),
  'push-permission-prompt': dynamic(() => import('./sources/push-permission-prompt').then((m) => m.PushPermissionPrompt), {
    ssr: false,
    loading: () => null,
  }),
  'recent-search-list': dynamic(() => import('./sources/recent-search-list').then((m) => m.RecentSearchList), {
    ssr: false,
    loading: () => null,
  }),
  'referral-waitlist-form': dynamic(() => import('./sources/referral-waitlist-form').then((m) => m.ReferralWaitlistForm), {
    ssr: false,
    loading: () => null,
  }),
  'refund-request-form': dynamic(() => import('./sources/refund-request-form').then((m) => m.RefundRequestForm), {
    ssr: false,
    loading: () => null,
  }),
  'refund-status-tracker': dynamic(() => import('./sources/refund-status-tracker').then((m) => m.RefundStatusTracker), {
    ssr: false,
    loading: () => null,
  }),
  'refunds-overview-table': dynamic(() => import('./sources/refunds-overview-table').then((m) => m.RefundsOverviewTable), {
    ssr: false,
    loading: () => null,
  }),
  'repair-request-form': dynamic(() => import('./sources/repair-request-form').then((m) => m.RepairRequestForm), {
    ssr: false,
    loading: () => null,
  }),
  'resume-document': dynamic(() => import('./sources/resume-document').then((m) => m.ResumeDocument), {
    ssr: false,
    loading: () => null,
  }),
  'retrieval-empty-state': dynamic(() => import('./sources/retrieval-empty-state').then((m) => m.RetrievalEmptyState), {
    ssr: false,
    loading: () => null,
  }),
  'retrieval-freshness-list': dynamic(() => import('./sources/retrieval-freshness-list').then((m) => m.RetrievalFreshnessList), {
    ssr: false,
    loading: () => null,
  }),
  'retrieval-index-status': dynamic(() => import('./sources/retrieval-index-status').then((m) => m.RetrievalIndexStatus), {
    ssr: false,
    loading: () => null,
  }),
  'return-exchange-picker': dynamic(() => import('./sources/return-exchange-picker').then((m) => m.ReturnExchangePicker), {
    ssr: false,
    loading: () => null,
  }),
  'return-label-instructions': dynamic(() => import('./sources/return-label-instructions').then((m) => m.ReturnLabelInstructions), {
    ssr: false,
    loading: () => null,
  }),
  'review-distribution-band': dynamic(() => import('./sources/review-distribution-band').then((m) => m.ReviewDistributionBand), {
    ssr: false,
    loading: () => null,
  }),
  'review-history-list': dynamic(() => import('./sources/review-history-list').then((m) => m.ReviewHistoryList), {
    ssr: false,
    loading: () => null,
  }),
  'review-list': dynamic(() => import('./sources/review-list').then((m) => m.ReviewList), {
    ssr: false,
    loading: () => null,
  }),
  'review-submit-form': dynamic(() => import('./sources/review-submit-form').then((m) => m.ReviewSubmitForm), {
    ssr: false,
    loading: () => null,
  }),
  'roadmap-columns': dynamic(() => import('./sources/roadmap-columns').then((m) => m.RoadmapColumns), {
    ssr: false,
    loading: () => null,
  }),
  'search-autocomplete': dynamic(() => import('./sources/search-autocomplete').then((m) => m.SearchAutocomplete), {
    ssr: false,
    loading: () => null,
  }),
  'search-facet-panel': dynamic(() => import('./sources/search-facet-panel').then((m) => m.SearchFacetPanel), {
    ssr: false,
    loading: () => null,
  }),
  'search-facet-range': dynamic(() => import('./sources/search-facet-range').then((m) => m.SearchFacetRange), {
    ssr: false,
    loading: () => null,
  }),
  'search-faceted-results': dynamic(() => import('./sources/search-faceted-results').then((m) => m.SearchFacetedResults), {
    ssr: false,
    loading: () => null,
  }),
  'search-results-panel': dynamic(() => import('./sources/search-results-panel').then((m) => m.SearchResultsPanel), {
    ssr: false,
    loading: () => null,
  }),
  'search-scope-switcher': dynamic(() => import('./sources/search-scope-switcher').then((m) => m.SearchScopeSwitcher), {
    ssr: false,
    loading: () => null,
  }),
  'security-faq-list': dynamic(() => import('./sources/security-faq-list').then((m) => m.SecurityFaqList), {
    ssr: false,
    loading: () => null,
  }),
  'security-posture-band': dynamic(() => import('./sources/security-posture-band').then((m) => m.SecurityPostureBand), {
    ssr: false,
    loading: () => null,
  }),
  'selection-ai-toolbar': dynamic(() => import('./sources/selection-ai-toolbar').then((m) => m.SelectionAiToolbar), {
    ssr: false,
    loading: () => null,
  }),
  'settings-api-keys': dynamic(() => import('./sources/settings-api-keys').then((m) => m.SettingsApiKeys), {
    ssr: false,
    loading: () => null,
  }),
  'settings-audit-log': dynamic(() => import('./sources/settings-audit-log').then((m) => m.SettingsAuditLog), {
    ssr: false,
    loading: () => null,
  }),
  'settings-danger-zone': dynamic(() => import('./sources/settings-danger-zone').then((m) => m.SettingsDangerZone), {
    ssr: false,
    loading: () => null,
  }),
  'settings-nav-layout': dynamic(() => import('./sources/settings-nav-layout').then((m) => m.SettingsNavLayout), {
    ssr: false,
    loading: () => null,
  }),
  'settings-notification-matrix': dynamic(() => import('./sources/settings-notification-matrix').then((m) => m.SettingsNotificationMatrix), {
    ssr: false,
    loading: () => null,
  }),
  'settings-profile-form': dynamic(() => import('./sources/settings-profile-form').then((m) => m.SettingsProfileForm), {
    ssr: false,
    loading: () => null,
  }),
  'settings-sessions': dynamic(() => import('./sources/settings-sessions').then((m) => m.SettingsSessions), {
    ssr: false,
    loading: () => null,
  }),
  'settings-team-members': dynamic(() => import('./sources/settings-team-members').then((m) => m.SettingsTeamMembers), {
    ssr: false,
    loading: () => null,
  }),
  'setup-wizard': dynamic(() => import('./sources/setup-wizard').then((m) => m.SetupWizard), {
    ssr: false,
    loading: () => null,
  }),
  'share-access-dialog': dynamic(() => import('./sources/share-access-dialog').then((m) => m.ShareAccessDialog), {
    ssr: false,
    loading: () => null,
  }),
  'sidebar-app-grouped': dynamic(() => import('./sources/sidebar-app-grouped').then((m) => m.SidebarAppGrouped), {
    ssr: false,
    loading: () => null,
  }),
  'sidebar-collapsible': dynamic(() => import('./sources/sidebar-collapsible').then((m) => m.SidebarCollapsible), {
    ssr: false,
    loading: () => null,
  }),
  'sidebar-docs-tree': dynamic(() => import('./sources/sidebar-docs-tree').then((m) => m.SidebarDocsTree), {
    ssr: false,
    loading: () => null,
  }),
  'sidebar-file-tree': dynamic(() => import('./sources/sidebar-file-tree').then((m) => m.SidebarFileTree), {
    ssr: false,
    loading: () => null,
  }),
  'sidebar-floating-inset': dynamic(() => import('./sources/sidebar-floating-inset').then((m) => m.SidebarFloatingInset), {
    ssr: false,
    loading: () => null,
  }),
  'sidebar-mail-folders': dynamic(() => import('./sources/sidebar-mail-folders').then((m) => m.SidebarMailFolders), {
    ssr: false,
    loading: () => null,
  }),
  'sidebar-nested-accordion': dynamic(() => import('./sources/sidebar-nested-accordion').then((m) => m.SidebarNestedAccordion), {
    ssr: false,
    loading: () => null,
  }),
  'sidebar-resizable': dynamic(() => import('./sources/sidebar-resizable').then((m) => m.SidebarResizable), {
    ssr: false,
    loading: () => null,
  }),
  'sidebar-thread-history': dynamic(() => import('./sources/sidebar-thread-history').then((m) => m.SidebarThreadHistory), {
    ssr: false,
    loading: () => null,
  }),
  'sidebar-two-pane': dynamic(() => import('./sources/sidebar-two-pane').then((m) => m.SidebarTwoPane), {
    ssr: false,
    loading: () => null,
  }),
  'sidebar-workspace-switcher': dynamic(() => import('./sources/sidebar-workspace-switcher').then((m) => m.SidebarWorkspaceSwitcher), {
    ssr: false,
    loading: () => null,
  }),
  'skeleton-list': dynamic(() => import('./sources/skeleton-list').then((m) => m.SkeletonList), {
    ssr: false,
    loading: () => null,
  }),
  'slide-over-panel': dynamic(() => import('./sources/slide-over-panel').then((m) => m.SlideOverPanel), {
    ssr: false,
    loading: () => null,
  }),
  'source-citation-list': dynamic(() => import('./sources/source-citation-list').then((m) => m.SourceCitationList), {
    ssr: false,
    loading: () => null,
  }),
  'sso-enterprise-split': dynamic(() => import('./sources/sso-enterprise-split').then((m) => m.SsoEnterpriseSplit), {
    ssr: false,
    loading: () => null,
  }),
  'stats-band': dynamic(() => import('./sources/stats-band').then((m) => m.StatsBand), {
    ssr: false,
    loading: () => null,
  }),
  'stats-benchmark-band': dynamic(() => import('./sources/stats-benchmark-band').then((m) => m.StatsBenchmarkBand), {
    ssr: false,
    loading: () => null,
  }),
  'stats-cards': dynamic(() => import('./sources/stats-cards').then((m) => m.StatsCards), {
    ssr: false,
    loading: () => null,
  }),
  'stats-comparison': dynamic(() => import('./sources/stats-comparison').then((m) => m.StatsComparison), {
    ssr: false,
    loading: () => null,
  }),
  'stats-narrative': dynamic(() => import('./sources/stats-narrative').then((m) => m.StatsNarrative), {
    ssr: false,
    loading: () => null,
  }),
  'stats-timeline': dynamic(() => import('./sources/stats-timeline').then((m) => m.StatsTimeline), {
    ssr: false,
    loading: () => null,
  }),
  'stock-availability-list': dynamic(() => import('./sources/stock-availability-list').then((m) => m.StockAvailabilityList), {
    ssr: false,
    loading: () => null,
  }),
  'subscription-cancel-flow': dynamic(() => import('./sources/subscription-cancel-flow').then((m) => m.SubscriptionCancelFlow), {
    ssr: false,
    loading: () => null,
  }),
  'support-chat-widget': dynamic(() => import('./sources/support-chat-widget').then((m) => m.SupportChatWidget), {
    ssr: false,
    loading: () => null,
  }),
  'support-ticket-form': dynamic(() => import('./sources/support-ticket-form').then((m) => m.SupportTicketForm), {
    ssr: false,
    loading: () => null,
  }),
  'support-ticket-thread': dynamic(() => import('./sources/support-ticket-thread').then((m) => m.SupportTicketThread), {
    ssr: false,
    loading: () => null,
  }),
  'team-grid': dynamic(() => import('./sources/team-grid').then((m) => m.TeamGrid), {
    ssr: false,
    loading: () => null,
  }),
  'team-invite-step': dynamic(() => import('./sources/team-invite-step').then((m) => m.TeamInviteStep), {
    ssr: false,
    loading: () => null,
  }),
  'testimonial-carousel': dynamic(() => import('./sources/testimonial-carousel').then((m) => m.TestimonialCarousel), {
    ssr: false,
    loading: () => null,
  }),
  'testimonial-grid': dynamic(() => import('./sources/testimonial-grid').then((m) => m.TestimonialGrid), {
    ssr: false,
    loading: () => null,
  }),
  'testimonial-ratings': dynamic(() => import('./sources/testimonial-ratings').then((m) => m.TestimonialRatings), {
    ssr: false,
    loading: () => null,
  }),
  'testimonial-spotlight': dynamic(() => import('./sources/testimonial-spotlight').then((m) => m.TestimonialSpotlight), {
    ssr: false,
    loading: () => null,
  }),
  'testimonial-video': dynamic(() => import('./sources/testimonial-video').then((m) => m.TestimonialVideo), {
    ssr: false,
    loading: () => null,
  }),
  'toast-stack': dynamic(() => import('./sources/toast-stack').then((m) => m.ToastStack), {
    ssr: false,
    loading: () => null,
  }),
  'upload-progress-list': dynamic(() => import('./sources/upload-progress-list').then((m) => m.UploadProgressList), {
    ssr: false,
    loading: () => null,
  }),
  'upload-requirements-form': dynamic(() => import('./sources/upload-requirements-form').then((m) => m.UploadRequirementsForm), {
    ssr: false,
    loading: () => null,
  }),
  'upload-resumable': dynamic(() => import('./sources/upload-resumable').then((m) => m.UploadResumable), {
    ssr: false,
    loading: () => null,
  }),
  'usage-meter-panel': dynamic(() => import('./sources/usage-meter-panel').then((m) => m.UsageMeterPanel), {
    ssr: false,
    loading: () => null,
  }),
  'usage-overage-notice': dynamic(() => import('./sources/usage-overage-notice').then((m) => m.UsageOverageNotice), {
    ssr: false,
    loading: () => null,
  }),
  'video-call-layout': dynamic(() => import('./sources/video-call-layout').then((m) => m.VideoCallLayout), {
    ssr: false,
    loading: () => null,
  }),
  'video-player-shell': dynamic(() => import('./sources/video-player-shell').then((m) => m.VideoPlayerShell), {
    ssr: false,
    loading: () => null,
  }),
  'voice-message-player': dynamic(() => import('./sources/voice-message-player').then((m) => m.VoiceMessagePlayer), {
    ssr: false,
    loading: () => null,
  }),
  'warranty-coverage-panel': dynamic(() => import('./sources/warranty-coverage-panel').then((m) => m.WarrantyCoveragePanel), {
    ssr: false,
    loading: () => null,
  }),
  'workspace-setup-form': dynamic(() => import('./sources/workspace-setup-form').then((m) => m.WorkspaceSetupForm), {
    ssr: false,
    loading: () => null,
  }),
}

/** The component type for one block, or undefined if it has no entry. */
export function getPlaygroundBlock(
  id: string,
): React.ComponentType<Record<string, unknown>> | undefined {
  return PLAYGROUND_BLOCKS[id]
}
