import 'server-only'

/**
 * Private collections in Firestore.
 *
 *   users/{uid}/collections/{collectionId}
 *     { id, name, description?, items: CollectionItem[], createdAt, updatedAt }
 *
 * One document per collection, with the items as a nested array rather than
 * a subcollection. That is the opposite of what `favorites` and `bundle` do,
 * and the reason is read shape: every surface that renders collections wants
 * all of them with their contents at once — the picker on a detail page has
 * to know which collections already contain this artifact. A subcollection
 * per collection would turn one query into N+1.
 *
 * The cap that makes it safe is `itemsPerCollection` (500). A Firestore
 * document is limited to ~1 MB; 500 items of four short strings is well
 * inside it, and `sanitizeCollection` truncates before anything reaches
 * here.
 *
 * Collection ids are client-generated UUIDs, so unlike effect ids they need
 * no percent-encoding — but they are still untrusted input, so `docId`
 * rejects anything that could escape the document path.
 */

import { adminDb } from '@/lib/firebase/admin'
import { Timestamp, type Firestore } from 'firebase-admin/firestore'
import {
  sanitizeCollection,
  sortCollections,
  type Collection,
} from '@/lib/collections'

/** Firestore commits at most 500 operations per batch. Stay under it. */
const BATCH_LIMIT = 450

function userDoc(db: Firestore, uid: string) {
  return db.collection('users').doc(uid)
}

/**
 * A safe document key, or null.
 *
 * Firestore forbids "/" in a document id and treats "." specially; ids
 * beginning "__" are reserved. Rejecting rather than encoding, because
 * unlike an effect id — which is catalog data we do not control — a
 * collection id is generated by our own client and has no business
 * containing any of them.
 */
function docId(id: string): string | null {
  if (!id || id.length > 64) return null
  if (!/^[A-Za-z0-9_-]+$/.test(id)) return null
  if (id.startsWith('__')) return null
  return id
}

/** Every collection the user owns, newest-touched first. */
export async function getCollections(uid: string): Promise<Collection[]> {
  const snap = await userDoc(adminDb(), uid).collection('collections').get()

  const collections = snap.docs.flatMap((doc) => {
    const data = doc.data()
    // Timestamps come back as Firestore Timestamps; the shared sanitizer
    // speaks ISO strings, so convert before validating rather than teaching
    // an isomorphic module about firebase-admin.
    const normalized = sanitizeCollection({
      ...data,
      id: doc.id,
      createdAt: toIso(data.createdAt),
      updatedAt: toIso(data.updatedAt),
    })
    return normalized ? [normalized] : []
  })

  return sortCollections(collections)
}

function toIso(value: unknown): string | undefined {
  if (value instanceof Timestamp) return value.toDate().toISOString()
  if (typeof value === 'string') return value
  return undefined
}

/**
 * Replace the user's collections wholesale.
 *
 * Same delete-what-is-gone, write-what-is-here shape as
 * `replaceSubcollection` in sync.ts, and for the same reasons: no instant
 * where the user has no collections, and no writes for rows that did not
 * change. It is not shared with that helper because the item array has to be
 * mapped into Firestore values here, and folding that in would have made the
 * generic helper take a serializer argument to serve two callers.
 */
export async function replaceCollections(
  uid: string,
  collections: Collection[],
): Promise<void> {
  const db = adminDb()
  const target = userDoc(db, uid).collection('collections')

  const documents = collections.flatMap((collection) => {
    const key = docId(collection.id)
    if (!key) return []
    return [
      {
        key,
        data: {
          id: collection.id,
          name: collection.name,
          // Firestore rejects `undefined`, so an absent description is an
          // absent field rather than a null one.
          ...(collection.description ? { description: collection.description } : {}),
          items: collection.items.map((item) => ({
            id: item.id,
            name: item.name,
            category: item.category,
            ...(item.level ? { level: item.level } : {}),
            addedAt: item.addedAt,
          })),
          createdAt: Timestamp.fromDate(new Date(collection.createdAt)),
          updatedAt: Timestamp.fromDate(new Date(collection.updatedAt)),
        },
      },
    ]
  })

  const existing = await target.select().get()
  const keep = new Set(documents.map((d) => d.key))
  const stale = existing.docs.filter((snap) => !keep.has(snap.id)).map((snap) => snap.ref)

  const batches: FirebaseFirestore.WriteBatch[] = []
  let batch = db.batch()
  let count = 0
  const rollIfFull = () => {
    if (count >= BATCH_LIMIT) {
      batches.push(batch)
      batch = db.batch()
      count = 0
    }
  }

  for (const ref of stale) {
    batch.delete(ref)
    count++
    rollIfFull()
  }
  for (const doc of documents) {
    batch.set(target.doc(doc.key), doc.data)
    count++
    rollIfFull()
  }
  batches.push(batch)

  // Sequential, not Promise.all — concurrent batches over one user's
  // documents contend and Firestore starts retrying.
  for (const b of batches) await b.commit()
}
