/**
 * Tag every effect with the colour its source is dominated by.
 *
 *     npx tsx scripts/build-effect-colors.mts
 *
 * Writes `src/lib/generated-effect-colors.json`, the table behind the colour
 * filter on /library and /browse. Extraction lives in
 * `src/lib/search/color.ts` and its header explains why an effect the source
 * does not clearly colour is left out of this file rather than guessed at.
 *
 * ── HOW IT RUNS ─────────────────────────────────────────────────────────
 *
 * `buildEffectColors()` is exported and `scripts/build-catalog-stats.mts`
 * calls it, so the table is regenerated by the existing `prebuild` step with
 * no new line in package.json. It also runs standalone (the block at the
 * bottom) for a quick look at coverage while tuning thresholds.
 *
 * ── THE SHAPE ───────────────────────────────────────────────────────────
 *
 *   { "buckets": ["red", …], "ids": { "red": "id-one id-two …", … } }
 *
 * Grouped by bucket, ids space-joined: 800-odd ids repeat nothing but the id
 * itself, which a bucket key would otherwise be repeated against every one
 * of. The client loads it on demand (dynamic import) rather than bundling
 * it, so it costs the page nothing until the colour filter is used.
 *
 * An effect can carry two buckets (a blue-to-indigo gradient is both), so the
 * lists overlap and the per-bucket counts sum to more than `tagged`.
 *
 * Only effects are tagged. Blocks, pages and templates are React styled with
 * theme tokens the consuming project supplies, so their colour is not a
 * property of the artifact.
 */

import { writeFileSync } from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, join } from 'node:path'
import { EFFECTS } from '../src/lib/effects.ts'
import { COLOR_BUCKETS, dominantColors, type ColorBucket } from '../src/lib/search/color.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, '..', 'src', 'lib', 'generated-effect-colors.json')

export interface EffectColorSummary {
  total: number
  tagged: number
  byBucket: Record<ColorBucket, number>
}

export function buildEffectColors(): EffectColorSummary {
  const byBucket = Object.fromEntries(COLOR_BUCKETS.map((b) => [b, [] as string[]])) as Record<
    ColorBucket,
    string[]
  >

  const tagged = new Set<string>()
  for (const e of EFFECTS) {
    // Shader effects paint with GLSL; whatever CSS they carry is layout.
    if ((e.renderer ?? 'css') !== 'css') continue
    const found = dominantColors(e.css ?? '', e.html ?? '')
    if (found.length > 0) tagged.add(e.id)
    for (const bucket of found) byBucket[bucket].push(e.id)
  }

  const payload = {
    buckets: COLOR_BUCKETS,
    ids: Object.fromEntries(COLOR_BUCKETS.map((b) => [b, byBucket[b].join(' ')])),
  }
  writeFileSync(OUT, JSON.stringify(payload) + '\n')

  const counts = Object.fromEntries(
    COLOR_BUCKETS.map((b) => [b, byBucket[b].length]),
  ) as Record<ColorBucket, number>
  const summary: EffectColorSummary = { total: EFFECTS.length, tagged: tagged.size, byBucket: counts }

  console.log(
    `[build-effect-colors] ${tagged.size}/${EFFECTS.length} effects tagged ` +
      `(${COLOR_BUCKETS.map((b) => `${b} ${counts[b]}`).join(', ')}) ` +
      `-> ${(JSON.stringify(payload).length / 1024).toFixed(1)} KB`,
  )
  return summary
}

// Run directly, not when imported by build-catalog-stats.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  buildEffectColors()
}
