// scripts/generate-effects.mjs
// Generates ~1100 unique CSS effects by combining templates with curated
// palettes, sizes, speeds, and gradient pairs. Output is a static JSON
// file consumed by src/lib/effects.ts.
//
// Run:  node scripts/generate-effects.mjs

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { generateExtra } from './generate-effects-extra.mjs'
import { generateExtra2 } from './generate-effects-extra2.mjs'
import { generateModern } from './generate-effects-modern.mjs'
import { generateModern2 } from './generate-effects-modern2.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT_PATH = join(__dirname, '..', 'src', 'lib', 'generated-effects.json')

/* ===== Design tokens ===== */

const PALETTES = [
  { name: 'Rose',    p: '#f43f5e', s: '#fb7185', a: '#fda4af', rgb: '244,63,94'  },
  { name: 'Pink',    p: '#ec4899', s: '#f472b6', a: '#f9a8d4', rgb: '236,72,153' },
  { name: 'Fuchsia', p: '#d946ef', s: '#e879f9', a: '#f0abfc', rgb: '217,70,239' },
  { name: 'Purple',  p: '#a855f7', s: '#c084fc', a: '#d8b4fe', rgb: '168,85,247' },
  { name: 'Violet',  p: '#8b5cf6', s: '#a78bfa', a: '#c4b5fd', rgb: '139,92,246' },
  { name: 'Indigo',  p: '#6366f1', s: '#818cf8', a: '#a5b4fc', rgb: '99,102,241' },
  { name: 'Blue',    p: '#3b82f6', s: '#60a5fa', a: '#93c5fd', rgb: '59,130,246' },
  { name: 'Sky',     p: '#0ea5e9', s: '#38bdf8', a: '#7dd3fc', rgb: '14,165,233' },
  { name: 'Cyan',    p: '#06b6d4', s: '#22d3ee', a: '#67e8f9', rgb: '6,182,212'  },
  { name: 'Teal',    p: '#14b8a6', s: '#2dd4bf', a: '#5eead4', rgb: '20,184,166' },
  { name: 'Emerald', p: '#10b981', s: '#34d399', a: '#6ee7b7', rgb: '16,185,129' },
  { name: 'Green',   p: '#22c55e', s: '#4ade80', a: '#86efac', rgb: '34,197,94'  },
  { name: 'Lime',    p: '#84cc16', s: '#a3e635', a: '#bef264', rgb: '132,204,22' },
  { name: 'Yellow',  p: '#eab308', s: '#facc15', a: '#fde047', rgb: '234,179,8'  },
  { name: 'Amber',   p: '#f59e0b', s: '#fbbf24', a: '#fcd34d', rgb: '245,158,11' },
  { name: 'Orange',  p: '#f97316', s: '#fb923c', a: '#fdba74', rgb: '249,115,22' },
  { name: 'Red',     p: '#ef4444', s: '#f87171', a: '#fca5a5', rgb: '239,68,68'  },
]

const SIZES = [
  { name: 'SM', pad: '0.4rem 0.9rem',  fs: '0.8rem',  rad: '0.4rem' },
  { name: 'MD', pad: '0.65rem 1.4rem', fs: '0.95rem', rad: '0.55rem' },
  { name: 'LG', pad: '0.85rem 1.8rem', fs: '1.1rem',  rad: '0.7rem' },
]

const SPEEDS = [
  { name: 'Fast',   d: '0.6s' },
  { name: 'Norm',   d: '1s'   },
  { name: 'Slow',   d: '1.6s' },
]

const GRADPAIRS = [
  { name: 'Sunset',   a: '#f43f5e', b: '#f59e0b' },
  { name: 'Ocean',    a: '#0ea5e9', b: '#6366f1' },
  { name: 'Forest',   a: '#10b981', b: '#84cc16' },
  { name: 'Berry',    a: '#d946ef', b: '#8b5cf6' },
  { name: 'Citrus',   a: '#f59e0b', b: '#84cc16' },
  { name: 'Flamingo', a: '#ec4899', b: '#f43f5e' },
  { name: 'Mint',     a: '#14b8a6', b: '#06b6d4' },
  { name: 'Twilight', a: '#6366f1', b: '#a855f7' },
  { name: 'Coral',    a: '#f97316', b: '#ec4899' },
  { name: 'Lagoon',   a: '#06b6d4', b: '#14b8a6' },
  { name: 'Fire',     a: '#ef4444', b: '#f59e0b' },
  { name: 'Galaxy',   a: '#8b5cf6', b: '#ec4899' },
]

const TRIOS = [
  { name: 'Rainbow', a: '#f43f5e', b: '#f59e0b', c: '#10b981' },
  { name: 'Cotton',  a: '#f472b6', b: '#a78bfa', c: '#60a5fa' },
  { name: 'Sunset',  a: '#f97316', b: '#ef4444', c: '#a855f7' },
  { name: 'Ocean',   a: '#06b6d4', b: '#3b82f6', c: '#6366f1' },
  { name: 'Forest',  a: '#22c55e', b: '#14b8a6', c: '#0ea5e9' },
  { name: 'Berry',   a: '#d946ef', b: '#a855f7', c: '#6366f1' },
  { name: 'Fire',    a: '#ef4444', b: '#f97316', c: '#fbbf24' },
  { name: 'Mint',    a: '#10b981', b: '#06b6d4', c: '#3b82f6' },
]

const NEUTRALS = [
  { name: 'Slate', bg: '#0f172a', surface: '#1e293b', border: '#334155', text: '#e2e8f0' },
  { name: 'Zinc',  bg: '#09090b', surface: '#18181b', border: '#27272a', text: '#e4e4e7' },
  { name: 'Stone', bg: '#1c1917', surface: '#292524', border: '#44403c', text: '#e7e5e4' },
  { name: 'Gray',  bg: '#111827', surface: '#1f2937', border: '#374151', text: '#e5e7eb' },
]

/* ===== Helpers ===== */

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
let _seq = 0
const seq = () => String(++_seq).padStart(4, '0')
const cls = (s) => `fx-${slug(s)}-${seq()}`

const effects = []
function add(e) { effects.push(e) }

/**
 * Build an effect object with normalized fields.
 * `klass` is the unique CSS class to use (already generated by caller).
 */
function mk({ name, category, description, html, css, tags = [], darkSurface = true, previewClass }) {
  return {
    id: slug(name) + '-' + seq(),
    name,
    category,
    description,
    html,
    css,
    tags,
    darkSurface,
    previewClass,
    generated: true,
  }
}

/* ============================================================
 *  BUTTONS  (target ~210)
 * ========================================================== */

// 1. Solid fill with hover lift — 17 palettes × 3 sizes = 51
for (const pal of PALETTES) {
  for (const sz of SIZES) {
    const c = cls(`btn-solid-${pal.name}-${sz.name}`)
    const html = `<button class="${c}">Click me</button>`
    const css = `.${c} {
  padding: ${sz.pad};
  font-size: ${sz.fs};
  font-weight: 600;
  color: #fff;
  border: none;
  border-radius: ${sz.rad};
  cursor: pointer;
  background: ${pal.p};
  box-shadow: 0 4px 14px 0 rgba(${pal.rgb}, 0.35);
  transition: transform 0.2s ease, box-shadow 0.2s ease, filter 0.2s ease;
}
.${c}:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 22px 0 rgba(${pal.rgb}, 0.45);
  filter: brightness(1.08);
}
.${c}:active { transform: translateY(0); }`
    add(mk({
      name: `Solid ${pal.name} ${sz.name} Button`,
      category: 'Buttons',
      description: `Solid ${pal.name.toLowerCase()} button with a soft glow shadow and lift-on-hover.`,
      html, css,
      tags: ['solid', pal.name.toLowerCase(), sz.name.toLowerCase(), 'lift', 'glow'],
    }))
  }
}

// 2. Gradient diagonal shift — 12 pairs × 3 sizes = 36
for (const g of GRADPAIRS) {
  for (const sz of SIZES) {
    const c = cls(`btn-grad-${g.name}-${sz.name}`)
    const html = `<button class="${c}">Get Started</button>`
    const css = `.${c} {
  padding: ${sz.pad};
  font-size: ${sz.fs};
  font-weight: 600;
  color: #fff;
  border: none;
  border-radius: ${sz.rad};
  cursor: pointer;
  background: linear-gradient(120deg, ${g.a}, ${g.b});
  background-size: 200% 200%;
  background-position: 0% 50%;
  box-shadow: 0 4px 14px 0 rgba(0,0,0,0.18);
  transition: background-position 0.5s ease, transform 0.2s ease, box-shadow 0.3s ease;
}
.${c}:hover {
  background-position: 100% 50%;
  transform: translateY(-2px);
  box-shadow: 0 10px 24px 0 rgba(0,0,0,0.25);
}`
    add(mk({
      name: `${g.name} Gradient ${sz.name} Button`,
      category: 'Buttons',
      description: `Diagonal ${g.name.toLowerCase()} gradient that slides across on hover, with lift and shadow.`,
      html, css,
      tags: ['gradient', g.name.toLowerCase(), sz.name.toLowerCase(), 'hover-shift'],
    }))
  }
}

// 3. Outline → fill on hover — 17 palettes × 3 sizes = 51
for (const pal of PALETTES) {
  for (const sz of SIZES) {
    const c = cls(`btn-outline-${pal.name}-${sz.name}`)
    const html = `<button class="${c}">Subscribe</button>`
    const css = `.${c} {
  padding: ${sz.pad};
  font-size: ${sz.fs};
  font-weight: 600;
  color: ${pal.p};
  background: transparent;
  border: 2px solid ${pal.p};
  border-radius: ${sz.rad};
  cursor: pointer;
  position: relative;
  overflow: hidden;
  transition: color 0.3s ease, box-shadow 0.3s ease;
  z-index: 0;
}
.${c}::before {
  content: '';
  position: absolute;
  inset: 0;
  background: ${pal.p};
  transform: scaleX(0);
  transform-origin: left;
  transition: transform 0.3s ease;
  z-index: -1;
}
.${c}:hover { color: #fff; box-shadow: 0 6px 18px 0 rgba(${pal.rgb}, 0.35); }
.${c}:hover::before { transform: scaleX(1); }`
    add(mk({
      name: `Outline Fill ${pal.name} ${sz.name} Button`,
      category: 'Buttons',
      description: `Outline ${pal.name.toLowerCase()} button that fills from left to right on hover.`,
      html, css,
      tags: ['outline', 'fill', pal.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

// 4. Glow pulse — 17 palettes × 3 sizes = 51
for (const pal of PALETTES) {
  for (const sz of SIZES) {
    const c = cls(`btn-glow-${pal.name}-${sz.name}`)
    const html = `<button class="${c}">Activate</button>`
    const css = `.${c} {
  padding: ${sz.pad};
  font-size: ${sz.fs};
  font-weight: 600;
  color: #fff;
  border: none;
  border-radius: ${sz.rad};
  cursor: pointer;
  background: ${pal.p};
  position: relative;
  transition: transform 0.2s ease;
}
.${c}::after {
  content: '';
  position: absolute;
  inset: 0;
  border-radius: ${sz.rad};
  box-shadow: 0 0 0 0 rgba(${pal.rgb}, 0.7);
  animation: ${c}-pulse 1.8s infinite;
}
@keyframes ${c}-pulse {
  0%   { box-shadow: 0 0 0 0 rgba(${pal.rgb}, 0.6); }
  70%  { box-shadow: 0 0 0 14px rgba(${pal.rgb}, 0); }
  100% { box-shadow: 0 0 0 0 rgba(${pal.rgb}, 0); }
}
.${c}:hover { transform: translateY(-2px); }`
    add(mk({
      name: `Glow Pulse ${pal.name} ${sz.name} Button`,
      category: 'Buttons',
      description: `${pal.name} button that emits a soft pulsing glow ring on an infinite loop.`,
      html, css,
      tags: ['glow', 'pulse', pal.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

// 5. Sheen sweep — 12 pairs × 3 sizes = 36 ... wait that's only 36 but I'll do all 12 pairs × 3 sizes
// Actually let's keep 12 × 3 = 36, total so far: 51+36+51+51+36 = 225. Slightly over 210 target. OK.

for (const g of GRADPAIRS) {
  for (const sz of SIZES) {
    const c = cls(`btn-sheen-${g.name}-${sz.name}`)
    const html = `<button class="${c}">Learn more</button>`
    const css = `.${c} {
  padding: ${sz.pad};
  font-size: ${sz.fs};
  font-weight: 600;
  color: #fff;
  border: none;
  border-radius: ${sz.rad};
  cursor: pointer;
  background: linear-gradient(120deg, ${g.a}, ${g.b});
  position: relative;
  overflow: hidden;
  transition: transform 0.2s ease;
}
.${c}::before {
  content: '';
  position: absolute;
  top: 0; left: -75%;
  width: 50%; height: 100%;
  background: linear-gradient(120deg, transparent, rgba(255,255,255,0.45), transparent);
  transform: skewX(-20deg);
  transition: left 0.6s ease;
}
.${c}:hover::before { left: 125%; }
.${c}:hover { transform: translateY(-2px); }`
    add(mk({
      name: `Sheen ${g.name} ${sz.name} Button`,
      category: 'Buttons',
      description: `${g.name} gradient button with a diagonal light sheen that sweeps across on hover.`,
      html, css,
      tags: ['sheen', 'shine', g.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

/* ============================================================
 *  LOADERS  (target ~165)
 * ========================================================== */

// 1. Spinner ring — 17 palettes × 3 speeds = 51
for (const pal of PALETTES) {
  for (const sp of SPEEDS) {
    const c = cls(`ld-spin-${pal.name}-${sp.name}`)
    const html = `<div class="${c}"></div>`
    const css = `.${c} {
  width: 38px; height: 38px;
  border: 4px solid rgba(${pal.rgb}, 0.2);
  border-top-color: ${pal.p};
  border-radius: 50%;
  animation: ${c}-rot ${sp.d} linear infinite;
}
@keyframes ${c}-rot { to { transform: rotate(360deg); } }`
    add(mk({
      name: `${pal.name} Ring Spinner (${sp.name})`,
      category: 'Loaders',
      description: `Classic ${sp.name.toLowerCase()} rotating ring spinner in ${pal.name.toLowerCase()}.`,
      html, css,
      tags: ['spinner', 'ring', pal.name.toLowerCase(), sp.name.toLowerCase()],
    }))
  }
}

// 2. Three-dot bounce — 12 pairs × 3 speeds = 36
for (const g of GRADPAIRS) {
  for (const sp of SPEEDS) {
    const c = cls(`ld-dots-${g.name}-${sp.name}`)
    const html = `<div class="${c}"><span></span><span></span><span></span></div>`
    const css = `.${c} { display: inline-flex; gap: 6px; }
.${c} span {
  width: 10px; height: 10px;
  border-radius: 50%;
  background: ${g.a};
  animation: ${c}-bounce ${sp.d} ease-in-out infinite;
}
.${c} span:nth-child(2) { background: ${g.b}; animation-delay: 0.15s; }
.${c} span:nth-child(3) { animation-delay: 0.3s; }
@keyframes ${c}-bounce {
  0%, 80%, 100% { transform: translateY(0); opacity: 0.6; }
  40% { transform: translateY(-10px); opacity: 1; }
}`
    add(mk({
      name: `${g.name} Bouncing Dots (${sp.name})`,
      category: 'Loaders',
      description: `Three bouncing dots in ${g.name.toLowerCase()} colors with staggered timing.`,
      html, css,
      tags: ['dots', 'bounce', g.name.toLowerCase(), sp.name.toLowerCase()],
    }))
  }
}

// 3. Pulse heartbeat — 17 palettes × 3 speeds = 51
for (const pal of PALETTES) {
  for (const sp of SPEEDS) {
    const c = cls(`ld-pulse-${pal.name}-${sp.name}`)
    const html = `<div class="${c}"></div>`
    const css = `.${c} {
  width: 36px; height: 36px;
  border-radius: 50%;
  background: ${pal.p};
  animation: ${c}-pulse ${sp.d} ease-in-out infinite;
}
@keyframes ${c}-pulse {
  0%, 100% { transform: scale(0.6); opacity: 0.6; box-shadow: 0 0 0 0 rgba(${pal.rgb}, 0.6); }
  50%      { transform: scale(1);   opacity: 1;   box-shadow: 0 0 0 12px rgba(${pal.rgb}, 0); }
}`
    add(mk({
      name: `${pal.name} Pulse Heartbeat (${sp.name})`,
      category: 'Loaders',
      description: `A ${pal.name.toLowerCase()} disc that pulses in size and emits an expanding ring.`,
      html, css,
      tags: ['pulse', 'heartbeat', pal.name.toLowerCase(), sp.name.toLowerCase()],
    }))
  }
}

// 4. Bar equalizer — 8 trios × 3 speeds = 24 ... I'll use just 8 trios
// Total: 51+36+51+24 = 162. ✓
for (const t of TRIOS) {
  for (const sp of SPEEDS) {
    const c = cls(`ld-bars-${t.name}-${sp.name}`)
    const html = `<div class="${c}"><span></span><span></span><span></span><span></span><span></span></div>`
    const css = `.${c} { display: inline-flex; gap: 4px; align-items: flex-end; height: 32px; }
.${c} span {
  width: 5px; height: 100%;
  background: ${t.a};
  border-radius: 3px;
  animation: ${c}-eq ${sp.d} ease-in-out infinite;
}
.${c} span:nth-child(2) { background: ${t.b}; animation-delay: 0.1s; }
.${c} span:nth-child(3) { animation-delay: 0.2s; }
.${c} span:nth-child(4) { background: ${t.c}; animation-delay: 0.3s; }
.${c} span:nth-child(5) { animation-delay: 0.4s; }
@keyframes ${c}-eq {
  0%, 100% { transform: scaleY(0.3); }
  50%      { transform: scaleY(1); }
}`
    add(mk({
      name: `${t.name} Equalizer Bars (${sp.name})`,
      category: 'Loaders',
      description: `Five-bar audio equalizer in ${t.name.toLowerCase()} colors with staggered heights.`,
      html, css,
      tags: ['bars', 'equalizer', t.name.toLowerCase(), sp.name.toLowerCase()],
    }))
  }
}

/* ============================================================
 *  CARDS  (target ~120)
 * ========================================================== */

// 1. Lift card with colored top border — 17 palettes × 3 sizes? Just 17 × 4 neutrals? Use 17 palettes × 1 = 17
// Actually I'll do: 17 palettes (top border color) × 4 neutral backgrounds = 68? Too many. Let's do 17 × 3 sizes for header height? Skip.
// Simpler: 17 palettes × 4 neutrals = 68. Plus hover lift variants. Let me do 17 × 4 = 68 lift cards + 17 × 3 gradient-border = 51. Total 119. ✓
for (const pal of PALETTES) {
  for (const neu of NEUTRALS) {
    const c = cls(`card-lift-${pal.name}-${neu.name}`)
    const html = `<div class="${c}"><h4>Card title</h4><p>Hover me to lift.</p></div>`
    const css = `.${c} {
  background: ${neu.surface};
  border: 1px solid ${neu.border};
  border-top: 4px solid ${pal.p};
  border-radius: 0.6rem;
  padding: 1.25rem;
  color: ${neu.text};
  width: 220px;
  box-shadow: 0 4px 14px rgba(0,0,0,0.15);
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}
.${c} h4 { margin: 0 0 0.4rem; font-size: 1rem; color: ${pal.s}; }
.${c} p  { margin: 0; font-size: 0.85rem; opacity: 0.8; }
.${c}:hover {
  transform: translateY(-6px);
  box-shadow: 0 18px 32px rgba(${pal.rgb}, 0.25);
}`
    add(mk({
      name: `${pal.name} Lift Card (${neu.name})`,
      category: 'Cards',
      description: `${neu.name} surface card with a ${pal.name.toLowerCase()} top accent bar; lifts with colored shadow on hover.`,
      html, css,
      tags: ['card', 'lift', pal.name.toLowerCase(), neu.name.toLowerCase()],
    }))
  }
}

// 2. Gradient border card — 12 pairs × 4 neutrals = 48, but I'll do 12 × 4 = 48? Total 68 + 48 = 116, ✓
for (const g of GRADPAIRS) {
  for (const neu of NEUTRALS) {
    const c = cls(`card-gb-${g.name}-${neu.name}`)
    const html = `<div class="${c}"><h4>${g.name} Border</h4><p>Animated gradient edge.</p></div>`
    const css = `.${c} {
  position: relative;
  background: ${neu.surface};
  border-radius: 0.7rem;
  padding: 1.25rem;
  color: ${neu.text};
  width: 220px;
}
.${c}::before {
  content: '';
  position: absolute;
  inset: -2px;
  border-radius: 0.8rem;
  background: linear-gradient(120deg, ${g.a}, ${g.b}, ${g.a});
  background-size: 200% 200%;
  z-index: -1;
  animation: ${c}-shift 3s linear infinite;
}
@keyframes ${c}-shift { to { background-position: 200% 0; } }
.${c} h4 { margin: 0 0 0.4rem; font-size: 1rem; color: ${g.a}; }
.${c} p  { margin: 0; font-size: 0.85rem; opacity: 0.8; }`
    add(mk({
      name: `${g.name} Gradient Border Card (${neu.name})`,
      category: 'Cards',
      description: `${neu.name} card with an animated ${g.name.toLowerCase()} gradient border that shifts continuously.`,
      html, css,
      tags: ['card', 'gradient-border', g.name.toLowerCase(), neu.name.toLowerCase()],
    }))
  }
}

/* ============================================================
 *  TEXT  (target ~135)
 * ========================================================== */

// 1. Gradient text — 12 pairs × 3 sizes = 36
for (const g of GRADPAIRS) {
  for (const sz of SIZES) {
    const c = cls(`txt-grad-${g.name}-${sz.name}`)
    const fs = sz.name === 'SM' ? '1.4rem' : sz.name === 'MD' ? '2rem' : '2.8rem'
    const html = `<h2 class="${c}">${g.name}</h2>`
    const css = `.${c} {
  margin: 0;
  font-size: ${fs};
  font-weight: 800;
  letter-spacing: -0.02em;
  background: linear-gradient(120deg, ${g.a}, ${g.b});
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
}`
    add(mk({
      name: `${g.name} Gradient Text (${sz.name})`,
      category: 'Text',
      description: `Static ${g.name.toLowerCase()} gradient text via background-clip.`,
      html, css,
      tags: ['gradient-text', g.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

// 2. Animated gradient text — 8 trios × 3 sizes = 24
for (const t of TRIOS) {
  for (const sz of SIZES) {
    const c = cls(`txt-anim-${t.name}-${sz.name}`)
    const fs = sz.name === 'SM' ? '1.4rem' : sz.name === 'MD' ? '2rem' : '2.8rem'
    const html = `<h2 class="${c}">${t.name}</h2>`
    const css = `.${c} {
  margin: 0;
  font-size: ${fs};
  font-weight: 800;
  background: linear-gradient(90deg, ${t.a}, ${t.b}, ${t.c}, ${t.a});
  background-size: 300% 100%;
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
  animation: ${c}-shift 4s linear infinite;
}
@keyframes ${c}-shift { to { background-position: 300% 0; } }`
    add(mk({
      name: `${t.name} Animated Gradient Text (${sz.name})`,
      category: 'Text',
      description: `Text filled with an animated ${t.name.toLowerCase()} gradient that flows horizontally.`,
      html, css,
      tags: ['animated-gradient', 'text', t.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

// 3. Glow text — 17 palettes × 3 sizes = 51
for (const pal of PALETTES) {
  for (const sz of SIZES) {
    const c = cls(`txt-glow-${pal.name}-${sz.name}`)
    const fs = sz.name === 'SM' ? '1.4rem' : sz.name === 'MD' ? '2rem' : '2.8rem'
    const html = `<h2 class="${c}">${pal.name}</h2>`
    const css = `.${c} {
  margin: 0;
  font-size: ${fs};
  font-weight: 800;
  color: ${pal.p};
  text-shadow:
    0 0 6px rgba(${pal.rgb}, 0.6),
    0 0 14px rgba(${pal.rgb}, 0.4),
    0 0 28px rgba(${pal.rgb}, 0.2);
}`
    add(mk({
      name: `${pal.name} Glow Text (${sz.name})`,
      category: 'Text',
      description: `${pal.name} text with a layered glow halo.`,
      html, css,
      tags: ['glow', 'text', pal.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

// 4. Gradient underline on hover — 12 pairs × 2 sizes (skip SM) = 24
// Total text: 36+24+51+24 = 135. ✓
for (const g of GRADPAIRS) {
  for (const sz of ['MD', 'LG']) {
    const c = cls(`txt-underline-${g.name}-${sz}`)
    const fs = sz === 'MD' ? '1.6rem' : '2.2rem'
    const html = `<a class="${c}">Hover to underline</a>`
    const css = `.${c} {
  font-size: ${fs};
  font-weight: 700;
  color: #fff;
  text-decoration: none;
  position: relative;
  cursor: pointer;
}
.${c}::after {
  content: '';
  position: absolute;
  left: 0; bottom: -4px;
  width: 100%; height: 3px;
  background: linear-gradient(90deg, ${g.a}, ${g.b});
  transform: scaleX(0);
  transform-origin: left;
  transition: transform 0.3s ease;
}
.${c}:hover::after { transform: scaleX(1); }`
    add(mk({
      name: `${g.name} Underline Reveal (${sz})`,
      category: 'Text',
      description: `Link text whose ${g.name.toLowerCase()} gradient underline grows in from the left on hover.`,
      html, css,
      tags: ['underline', 'link', g.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

/* ============================================================
 *  BACKGROUNDS  (target ~120)
 * ========================================================== */

// 1. Animated gradient bg — 8 trios × 3 speeds = 24
for (const t of TRIOS) {
  for (const sp of SPEEDS) {
    const c = cls(`bg-grad-${t.name}-${sp.name}`)
    const html = `<div class="${c}"></div>`
    const css = `.${c} {
  width: 100%; height: 100%;
  min-height: 160px;
  border-radius: 0.5rem;
  background: linear-gradient(120deg, ${t.a}, ${t.b}, ${t.c}, ${t.a});
  background-size: 300% 300%;
  animation: ${c}-flow ${sp.d} ease infinite;
}
@keyframes ${c}-flow {
  0%   { background-position: 0% 50%; }
  50%  { background-position: 100% 50%; }
  100% { background-position: 0% 50%; }
}`
    add(mk({
      name: `${t.name} Flowing Gradient (${sp.name})`,
      category: 'Backgrounds',
      description: `Full-bleed animated ${t.name.toLowerCase()} gradient that flows diagonally on a loop.`,
      html, css,
      tags: ['gradient-bg', 'animated', t.name.toLowerCase(), sp.name.toLowerCase()],
    }))
  }
}

// 2. Radial glow bg — 17 palettes × 4 neutrals = 68
for (const pal of PALETTES) {
  for (const neu of NEUTRALS) {
    const c = cls(`bg-glow-${pal.name}-${neu.name}`)
    const html = `<div class="${c}"></div>`
    const css = `.${c} {
  width: 100%; height: 100%;
  min-height: 160px;
  border-radius: 0.5rem;
  background:
    radial-gradient(circle at 30% 30%, rgba(${pal.rgb}, 0.45), transparent 50%),
    radial-gradient(circle at 70% 70%, rgba(${pal.rgb}, 0.25), transparent 50%),
    ${neu.bg};
}`
    add(mk({
      name: `${pal.name} Glow Field (${neu.name})`,
      category: 'Backgrounds',
      description: `${neu.name} background with two soft ${pal.name.toLowerCase()} radial glows in opposite corners.`,
      html, css,
      tags: ['radial', 'glow', pal.name.toLowerCase(), neu.name.toLowerCase()],
    }))
  }
}

// 3. Striped bg — 12 pairs × 2 directions = 24, + 4 conic? Let's do 12 × 2 = 24 + 12 × 1 = 12 = 36, but cap at 28.
// Actually total so far: 24 + 68 = 92. Need 28 more. Do 12 pairs × 2 = 24 stripes + 4 conic trios = 28. ✓
for (const g of GRADPAIRS) {
  for (const dir of ['diagonal', 'vertical']) {
    const c = cls(`bg-stripe-${g.name}-${dir}`)
    const ang = dir === 'diagonal' ? '45deg' : '90deg'
    const html = `<div class="${c}"></div>`
    const css = `.${c} {
  width: 100%; height: 100%;
  min-height: 160px;
  border-radius: 0.5rem;
  background: repeating-linear-gradient(${ang}, ${g.a} 0 14px, ${g.b} 14px 28px);
}`
    add(mk({
      name: `${g.name} Stripes (${dir})`,
      category: 'Backgrounds',
      description: `Tight ${dir} ${g.name.toLowerCase()} stripe pattern via repeating-linear-gradient.`,
      html, css,
      tags: ['stripes', 'pattern', g.name.toLowerCase(), dir],
    }))
  }
}

for (const t of TRIOS.slice(0, 4)) {
  const c = cls(`bg-conic-${t.name}`)
  const html = `<div class="${c}"></div>`
  const css = `.${c} {
  width: 100%; height: 100%;
  min-height: 160px;
  border-radius: 0.5rem;
  background: conic-gradient(from 0deg, ${t.a}, ${t.b}, ${t.c}, ${t.a});
  animation: ${c}-rot 6s linear infinite;
}
@keyframes ${c}-rot { to { transform: rotate(360deg); } }`
  add(mk({
    name: `${t.name} Conic Swirl`,
    category: 'Backgrounds',
    description: `Rotating ${t.name.toLowerCase()} conic gradient that swirls around the center.`,
    html, css,
    tags: ['conic', 'swirl', t.name.toLowerCase()],
  }))
}

/* ============================================================
 *  INPUTS & HOVER  (target ~120)
 * ========================================================== */

// 1. Floating label input — 17 palettes × 3 sizes = 51
for (const pal of PALETTES) {
  for (const sz of SIZES) {
    const c = cls(`inp-fl-${pal.name}-${sz.name}`)
    const pad = sz.pad, fs = sz.fs, rad = sz.rad
    // Capture the seq value ONCE so input id and label for match — without
    // this, the label's `for="x"` doesn't match `id="x1234"` and clicking
    // the label won't focus the input.
    const inputId = `inp-${seq()}`
    const html = `<div class="${c}"><input id="${inputId}" placeholder=" " /><label for="${inputId}">Email</label></div>`
    const css = `.${c} { position: relative; width: 220px; }
.${c} input {
  width: 100%;
  padding: ${pad};
  font-size: ${fs};
  color: #e5e7eb;
  background: rgba(255,255,255,0.04);
  border: 1px solid rgba(255,255,255,0.18);
  border-radius: ${rad};
  outline: none;
  transition: border-color 0.2s ease, box-shadow 0.2s ease;
}
.${c} input:focus {
  border-color: ${pal.p};
  box-shadow: 0 0 0 3px rgba(${pal.rgb}, 0.25);
}
.${c} label {
  position: absolute;
  left: 0.8rem; top: 50%;
  transform: translateY(-50%);
  font-size: ${fs};
  color: #9ca3af;
  pointer-events: none;
  transition: all 0.2s ease;
  background: ${pal.p};
  padding: 0 4px;
  border-radius: 3px;
  color: #fff;
}
.${c} input:focus + label,
.${c} input:not(:placeholder-shown) + label {
  top: 0;
  font-size: 0.7rem;
  transform: translateY(-50%);
}`
    add(mk({
      name: `${pal.name} Floating Label (${sz.name})`,
      category: 'Inputs & Hover',
      description: `${pal.name} input whose label floats above on focus or when filled.`,
      html, css,
      tags: ['input', 'floating-label', pal.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

// 2. Underline grow input — 12 pairs × 3 sizes = 36
for (const g of GRADPAIRS) {
  for (const sz of SIZES) {
    const c = cls(`inp-ug-${g.name}-${sz.name}`)
    const fs = sz.fs, pad = sz.pad
    const html = `<input class="${c}" placeholder="Type here…" />`
    const css = `.${c} {
  width: 220px;
  padding: ${pad};
  font-size: ${fs};
  color: #e5e7eb;
  background: transparent;
  border: none;
  border-bottom: 2px solid rgba(255,255,255,0.25);
  outline: none;
  position: relative;
}
.${c}::after { content: ''; }
/* Use wrapper trick: simulate via background-image */
.${c} {
  background-image: linear-gradient(90deg, ${g.a}, ${g.b});
  background-size: 0% 2px;
  background-repeat: no-repeat;
  background-position: 0 100%;
  transition: background-size 0.3s ease, border-color 0.3s ease;
}
.${c}:focus {
  border-bottom-color: transparent;
  background-size: 100% 2px;
}`
    add(mk({
      name: `${g.name} Underline Grow (${sz.name})`,
      category: 'Inputs & Hover',
      description: `Minimal input whose ${g.name.toLowerCase()} underline grows from left on focus.`,
      html, css,
      tags: ['input', 'underline', g.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

// 3. Image zoom on hover — 8 trios × 4 neutrals = 32... but need 33 more. Do 8 × 4 = 32, plus 1? Just do 8 × 4 = 32. Total: 51+36+32 = 119. Close enough to 120. ✓
for (const t of TRIOS) {
  for (const neu of NEUTRALS) {
    const c = cls(`hov-zoom-${t.name}-${neu.name}`)
    const html = `<div class="${c}"><div class="${c}-inner"></div></div>`
    const css = `.${c} {
  width: 180px; height: 120px;
  border-radius: 0.6rem;
  overflow: hidden;
  border: 1px solid ${neu.border};
  background: ${neu.surface};
}
.${c}-inner {
  width: 100%; height: 100%;
  background: linear-gradient(120deg, ${t.a}, ${t.b}, ${t.c});
  transition: transform 0.4s ease;
}
.${c}:hover .${c}-inner { transform: scale(1.12); }`
    add(mk({
      name: `${t.name} Zoom Tile (${neu.name})`,
      category: 'Inputs & Hover',
      description: `${neu.name} framed tile whose ${t.name.toLowerCase()} content zooms in on hover.`,
      html, css,
      tags: ['hover', 'zoom', 'image', t.name.toLowerCase(), neu.name.toLowerCase()],
    }))
  }
}

/* ============================================================
 *  NAVIGATION & MENUS  (target ~80)
 * ========================================================== */

// 1. Pill nav with sliding indicator — 17 palettes × 4 neutrals = 68, + 12 dropdown? Just 68 + 12 = 80. ✓
for (const pal of PALETTES) {
  for (const neu of NEUTRALS) {
    const c = cls(`nav-pill-${pal.name}-${neu.name}`)
    const html = `<nav class="${c}"><a class="active">Home</a><a>Docs</a><a>Pricing</a><a>About</a></nav>`
    const css = `.${c} {
  display: inline-flex;
  gap: 4px;
  padding: 4px;
  background: ${neu.surface};
  border: 1px solid ${neu.border};
  border-radius: 999px;
}
.${c} a {
  padding: 0.4rem 0.9rem;
  font-size: 0.85rem;
  font-weight: 500;
  color: ${neu.text};
  border-radius: 999px;
  cursor: pointer;
  transition: color 0.2s ease, background 0.2s ease;
}
.${c} a:hover { color: ${pal.s}; }
.${c} a.active {
  color: #fff;
  background: ${pal.p};
  box-shadow: 0 2px 8px rgba(${pal.rgb}, 0.45);
}`
    add(mk({
      name: `${pal.name} Pill Nav (${neu.name})`,
      category: 'Navigation & Menus',
      description: `${neu.name} pill nav with the active item highlighted in ${pal.name.toLowerCase()}.`,
      html, css,
      tags: ['nav', 'pill', pal.name.toLowerCase(), neu.name.toLowerCase()],
    }))
  }
}

// 2. Underline nav — 12 pairs × 1 = 12
for (const g of GRADPAIRS) {
  const c = cls(`nav-underline-${g.name}`)
  const html = `<nav class="${c}"><a class="active">Home</a><a>Blog</a><a>Contact</a></nav>`
  const css = `.${c} { display: inline-flex; gap: 1.5rem; }
.${c} a {
  position: relative;
  font-size: 0.95rem;
  font-weight: 600;
  color: #9ca3af;
  cursor: pointer;
  padding-bottom: 6px;
  transition: color 0.2s ease;
}
.${c} a:hover { color: #fff; }
.${c} a.active { color: #fff; }
.${c} a.active::after {
  content: '';
  position: absolute;
  left: 0; bottom: 0;
  width: 100%; height: 2px;
  background: linear-gradient(90deg, ${g.a}, ${g.b});
  border-radius: 2px;
}`
  add(mk({
    name: `${g.name} Underline Nav`,
    category: 'Navigation & Menus',
    description: `Inline nav with active item marked by a ${g.name.toLowerCase()} gradient underline.`,
    html, css,
    tags: ['nav', 'underline', g.name.toLowerCase()],
  }))
}

/* ============================================================
 *  DIVIDERS & SEPARATORS  (target ~80)
 * ========================================================== */

// 1. Gradient divider line — 12 pairs × 3 thicknesses = 36
// The divider is wrapped in a context block (heading + paragraph above/below)
// so the preview shows the divider IN USE rather than as a 1px sliver in a
// 180px-tall container that looks blank.
for (const g of GRADPAIRS) {
  for (const th of [{ n: 'Thin', h: '1px' }, { n: 'Med', h: '2px' }, { n: 'Thick', h: '4px' }]) {
    const c = cls(`div-line-${g.name}-${th.n}`)
    const html = `<div class="${c}">
  <p class="pre">Introduction</p>
  <div class="rule"></div>
  <p class="post">Body content follows below.</p>
</div>`
    const css = `.${c} {
  width: 100%; max-width: 280px;
  display: flex; flex-direction: column; gap: 0.6rem;
  color: #cbd5e1; font-family: system-ui, sans-serif;
}
.${c} .pre {
  margin: 0;
  font-size: 0.85rem; font-weight: 700; color: #f1f5f9;
  letter-spacing: -0.01em;
}
.${c} .post {
  margin: 0;
  font-size: 0.78rem; color: #94a3b8; line-height: 1.4;
}
.${c} .rule {
  width: 100%; height: ${th.h};
  background: linear-gradient(90deg, transparent, ${g.a}, ${g.b}, transparent);
  border-radius: ${th.h};
}`
    add(mk({
      name: `${g.name} Divider (${th.n})`,
      category: 'Dividers & Separators',
      description: `Fading ${g.name.toLowerCase()} gradient divider line (${th.n.toLowerCase()} thickness), shown between two text blocks.`,
      html, css,
      tags: ['divider', 'gradient', g.name.toLowerCase(), th.n.toLowerCase()],
    }))
  }
}

// 2. Dashed divider — 17 palettes × 2 styles = 34
// Total: 36 + 34 = 70. Need 10 more. Add 8 trios × 1 + 4 = 12 → 82. ✓
for (const pal of PALETTES) {
  for (const style of ['dashed', 'dotted']) {
    const c = cls(`div-${style}-${pal.name}`)
    const html = `<div class="${c}">
  <span class="label">${pal.name}</span>
  <span class="rule"></span>
  <span class="meta">Section break</span>
</div>`
    const css = `.${c} {
  width: 100%; max-width: 280px;
  display: flex; align-items: center; gap: 0.75rem;
  color: #cbd5e1; font-family: system-ui, sans-serif;
}
.${c} .label {
  font-size: 0.7rem; font-weight: 700;
  text-transform: uppercase; letter-spacing: 0.08em;
  color: ${pal.p};
  white-space: nowrap;
}
.${c} .rule {
  flex: 1; height: 0;
  border-top: 2px ${style} ${pal.p};
  opacity: 0.85;
}
.${c} .meta {
  font-size: 0.7rem; color: #64748b;
  white-space: nowrap;
}`
    add(mk({
      name: `${pal.name} ${style.charAt(0).toUpperCase() + style.slice(1)} Divider`,
      category: 'Dividers & Separators',
      description: `Full-width ${style} ${pal.name.toLowerCase()} divider with a labeled section break.`,
      html, css,
      tags: ['divider', style, pal.name.toLowerCase()],
    }))
  }
}

for (const t of TRIOS.slice(0, 4)) {
  const c = cls(`div-tri-${t.name}`)
  const html = `<div class="${c}">
  <span class="dot"></span>
  <span class="bar"></span>
  <span class="bar"></span>
  <span class="bar"></span>
  <span class="dot"></span>
</div>`
  const css = `.${c} {
  width: 100%; max-width: 280px;
  display: flex; align-items: center; gap: 8px;
}
.${c} .dot {
  width: 8px; height: 8px; border-radius: 50%;
  background: ${t.a}; flex-shrink: 0;
  box-shadow: 0 0 8px ${t.a};
}
.${c} .bar {
  flex: 1; height: 3px; border-radius: 2px;
}
.${c} .bar:nth-child(2) { background: ${t.a}; }
.${c} .bar:nth-child(3) { background: ${t.b}; }
.${c} .bar:nth-child(4) { background: ${t.c}; }`
  add(mk({
    name: `${t.name} Tri-Color Divider`,
    category: 'Dividers & Separators',
    description: `Three-segment divider with end dots using the ${t.name.toLowerCase()} palette.`,
    html, css,
    tags: ['divider', 'tri-color', t.name.toLowerCase()],
  }))
}

/* ============================================================
 *  BADGES & TAGS  (target ~100)
 * ========================================================== */

// 1. Solid badge — 17 palettes × 3 sizes = 51
// Each badge preview shows a labeled header + a row of three example badges
// (Status / Featured / New) so the preview reads as a real UI fragment rather
// than a single tiny pill floating in a 180px container.
for (const pal of PALETTES) {
  for (const sz of SIZES) {
    const c = cls(`bdg-solid-${pal.name}-${sz.name}`)
    const fs = sz.name === 'SM' ? '0.65rem' : sz.name === 'MD' ? '0.75rem' : '0.85rem'
    const pad = sz.name === 'SM' ? '0.15rem 0.5rem' : sz.name === 'MD' ? '0.2rem 0.65rem' : '0.25rem 0.8rem'
    const html = `<div class="${c}">
  <span class="hdr">${pal.name} badges</span>
  <div class="row">
    <span class="badge">Status</span>
    <span class="badge">Featured</span>
    <span class="badge">New</span>
  </div>
</div>`
    const css = `.${c} {
  display: flex; flex-direction: column; gap: 0.5rem;
  font-family: system-ui, sans-serif;
}
.${c} .hdr {
  font-size: 0.7rem; font-weight: 700;
  text-transform: uppercase; letter-spacing: 0.08em;
  color: #94a3b8;
}
.${c} .row { display: flex; flex-wrap: wrap; gap: 0.4rem; }
.${c} .badge {
  display: inline-flex;
  align-items: center;
  padding: ${pad};
  font-size: ${fs};
  font-weight: 700;
  color: #fff;
  background: ${pal.p};
  border-radius: 999px;
  letter-spacing: 0.03em;
  text-transform: uppercase;
}`
    add(mk({
      name: `${pal.name} Solid Badge (${sz.name})`,
      category: 'Badges & Tags',
      description: `Solid ${pal.name.toLowerCase()} pill badge in three example labels.`,
      html, css,
      tags: ['badge', 'solid', pal.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

// 2. Outline badge — 17 palettes × 3 sizes = 51
// Total: 51 + 51 = 102. ✓
for (const pal of PALETTES) {
  for (const sz of SIZES) {
    const c = cls(`bdg-out-${pal.name}-${sz.name}`)
    const fs = sz.name === 'SM' ? '0.65rem' : sz.name === 'MD' ? '0.75rem' : '0.85rem'
    const pad = sz.name === 'SM' ? '0.15rem 0.5rem' : sz.name === 'MD' ? '0.2rem 0.65rem' : '0.25rem 0.8rem'
    const html = `<div class="${c}">
  <span class="hdr">${pal.name} outline</span>
  <div class="row">
    <span class="badge">Open</span>
    <span class="badge">Pending</span>
    <span class="badge">Review</span>
  </div>
</div>`
    const css = `.${c} {
  display: flex; flex-direction: column; gap: 0.5rem;
  font-family: system-ui, sans-serif;
}
.${c} .hdr {
  font-size: 0.7rem; font-weight: 700;
  text-transform: uppercase; letter-spacing: 0.08em;
  color: #94a3b8;
}
.${c} .row { display: flex; flex-wrap: wrap; gap: 0.4rem; }
.${c} .badge {
  display: inline-flex;
  align-items: center;
  padding: ${pad};
  font-size: ${fs};
  font-weight: 700;
  color: ${pal.p};
  background: rgba(${pal.rgb}, 0.1);
  border: 1px solid ${pal.p};
  border-radius: 999px;
  letter-spacing: 0.03em;
  text-transform: uppercase;
}`
    add(mk({
      name: `${pal.name} Outline Badge (${sz.name})`,
      category: 'Badges & Tags',
      description: `Translucent ${pal.name.toLowerCase()} outline pill badge in three example labels.`,
      html, css,
      tags: ['badge', 'outline', pal.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

/* ============================================================
 *  TOGGLES & SWITCHES  (target ~120)
 * ========================================================== */

// 1. iOS-style switch — 17 palettes × 3 sizes = 51
for (const pal of PALETTES) {
  for (const sz of SIZES) {
    const c = cls(`tgl-ios-${pal.name}-${sz.name}`)
    const w = sz.name === 'SM' ? 36 : sz.name === 'MD' ? 48 : 60
    const h = Math.round(w * 0.55)
    const knob = h - 6
    const travel = w - h
    const html = `<div class="${c}">
  <label class="row"><input type="checkbox" checked /><span class="track"><span class="knob"></span></span><span class="lbl">Notifications</span></label>
  <label class="row"><input type="checkbox" /><span class="track"><span class="knob"></span></span><span class="lbl">Dark mode</span></label>
</div>`
    const css = `.${c} { display: flex; flex-direction: column; gap: 0.7rem; color: #cbd5e1; font-family: system-ui, sans-serif; }
.${c} .row { display: inline-flex; align-items: center; gap: 0.6rem; cursor: pointer; }
.${c} input { display: none; }
.${c} .track {
  width: ${w}px; height: ${h}px;
  border-radius: 999px;
  background: rgba(255,255,255,0.18);
  position: relative;
  transition: background 0.25s ease;
  flex-shrink: 0;
}
.${c} .knob {
  position: absolute;
  top: 3px; left: 3px;
  width: ${knob}px; height: ${knob}px;
  border-radius: 50%;
  background: #fff;
  box-shadow: 0 2px 6px rgba(0,0,0,0.3);
  transition: transform 0.25s cubic-bezier(0.4, 0, 0.2, 1);
}
.${c} .lbl { font-size: 0.78rem; color: #cbd5e1; }
.${c} input:checked + .track { background: ${pal.p}; box-shadow: 0 0 12px rgba(${pal.rgb}, 0.5); }
.${c} input:checked + .track .knob { transform: translateX(${travel}px); }`
    add(mk({
      name: `${pal.name} iOS Switch (${sz.name})`,
      category: 'Toggles & Switches',
      description: `iOS-style toggle that slides a knob and lights up ${pal.name.toLowerCase()} when on. Shown in both ON and OFF states with labels.`,
      html, css,
      tags: ['toggle', 'switch', 'ios', pal.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

// 2. Square flip switch — 12 pairs × 3 sizes = 36
for (const g of GRADPAIRS) {
  for (const sz of SIZES) {
    const c = cls(`tgl-flip-${g.name}-${sz.name}`)
    const s = sz.name === 'SM' ? 28 : sz.name === 'MD' ? 36 : 48
    const html = `<div class="${c}">
  <label class="row"><input type="checkbox" checked /><span class="track"><span class="knob"></span></span><span class="lbl">Enabled</span></label>
  <label class="row"><input type="checkbox" /><span class="track"><span class="knob"></span></span><span class="lbl">Disabled</span></label>
</div>`
    const css = `.${c} { display: flex; flex-direction: column; gap: 0.7rem; color: #cbd5e1; font-family: system-ui, sans-serif; }
.${c} .row { display: inline-flex; align-items: center; gap: 0.6rem; cursor: pointer; }
.${c} input { display: none; }
.${c} .track {
  width: ${s * 2}px; height: ${s}px;
  border-radius: 6px;
  background: rgba(255,255,255,0.12);
  position: relative;
  overflow: hidden;
  transition: background 0.3s ease;
  flex-shrink: 0;
}
.${c} .knob {
  position: absolute;
  top: 0; left: 0;
  width: ${s}px; height: ${s}px;
  background: linear-gradient(135deg, ${g.a}, ${g.b});
  transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}
.${c} .lbl { font-size: 0.78rem; color: #cbd5e1; }
.${c} input:checked + .track { background: rgba(${[parseInt(g.a.slice(1,3),16), parseInt(g.a.slice(3,5),16), parseInt(g.a.slice(5,7),16)].join(',')}, 0.18); }
.${c} input:checked + .track .knob { transform: translateX(${s}px); }`
    add(mk({
      name: `${g.name} Flip Switch (${sz.name})`,
      category: 'Toggles & Switches',
      description: `Square-edged switch with a ${g.name.toLowerCase()} gradient knob that slides horizontally. Shown in both states with labels.`,
      html, css,
      tags: ['toggle', 'switch', 'flip', g.name.toLowerCase(), sz.name.toLowerCase()],
    }))
  }
}

// 3. Round pulse toggle — 17 palettes × 2 sizes = 34... I'll do 17 × 2 = 34. Total: 51 + 36 + 34 = 121. ✓
for (const pal of PALETTES) {
  for (const sz of ['SM', 'MD']) {
    const c = cls(`tgl-pulse-${pal.name}-${sz}`)
    const s = sz === 'SM' ? 26 : 34
    const html = `<div class="${c}">
  <label class="row"><input type="checkbox" checked /><span class="track"><span class="knob"></span></span><span class="lbl">Active</span></label>
  <label class="row"><input type="checkbox" /><span class="track"><span class="knob"></span></span><span class="lbl">Inactive</span></label>
</div>`
    const css = `.${c} { display: flex; flex-direction: column; gap: 0.7rem; color: #cbd5e1; font-family: system-ui, sans-serif; }
.${c} .row { display: inline-flex; align-items: center; gap: 0.6rem; cursor: pointer; }
.${c} input { display: none; }
.${c} .track {
  width: ${s * 2}px; height: ${s}px;
  border-radius: 999px;
  background: rgba(255,255,255,0.12);
  position: relative;
  transition: background 0.3s ease;
  flex-shrink: 0;
}
.${c} .knob {
  position: absolute;
  top: 3px; left: 3px;
  width: ${s - 6}px; height: ${s - 6}px;
  border-radius: 50%;
  background: ${pal.p};
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}
.${c} .lbl { font-size: 0.78rem; color: #cbd5e1; }
.${c} input:checked + .track { background: rgba(${pal.rgb}, 0.2); }
.${c} input:checked + .track .knob {
  transform: translateX(${s}px);
  box-shadow: 0 0 0 4px rgba(${pal.rgb}, 0.25), 0 0 12px rgba(${pal.rgb}, 0.6);
}`
    add(mk({
      name: `${pal.name} Pulse Toggle (${sz})`,
      category: 'Toggles & Switches',
      description: `Round toggle whose ${pal.name.toLowerCase()} knob glows and emits a halo when on. Shown in both states with labels.`,
      html, css,
      tags: ['toggle', 'switch', 'pulse', pal.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

/* ============================================================
 *  TOOLTIPS & POPOVERS  (target ~96)
 * ========================================================== */

// 1. Top tooltip with arrow — 17 palettes × 2 sizes = 34
for (const pal of PALETTES) {
  for (const sz of ['SM', 'MD']) {
    const c = cls(`tip-top-${pal.name}-${sz}`)
    const fs = sz === 'SM' ? '0.7rem' : '0.8rem'
    const pad = sz === 'SM' ? '0.3rem 0.6rem' : '0.4rem 0.8rem'
    const html = `<div class="${c}"><button>Hover me</button><span class="tip">Tooltip</span></div>`
    const css = `.${c} { position: relative; display: inline-block; }
.${c} button {
  padding: 0.5rem 1rem;
  font-size: 0.85rem;
  color: ${pal.p};
  background: rgba(${pal.rgb}, 0.1);
  border: 1px solid ${pal.p};
  border-radius: 0.4rem;
  cursor: pointer;
}
.${c} .tip {
  position: absolute;
  bottom: calc(100% + 8px);
  left: 50%;
  transform: translateX(-50%) translateY(4px);
  padding: ${pad};
  font-size: ${fs};
  font-weight: 500;
  color: #fff;
  background: ${pal.p};
  border-radius: 0.35rem;
  white-space: nowrap;
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.2s ease, transform 0.2s ease;
}
.${c} .tip::after {
  content: '';
  position: absolute;
  top: 100%; left: 50%;
  transform: translateX(-50%);
  border: 5px solid transparent;
  border-top-color: ${pal.p};
}
.${c}:hover .tip {
  opacity: 1;
  transform: translateX(-50%) translateY(0);
}`
    add(mk({
      name: `${pal.name} Top Tooltip (${sz})`,
      category: 'Tooltips & Popovers',
      description: `Tooltip that fades in above the trigger with a ${pal.name.toLowerCase()} arrow.`,
      html, css,
      tags: ['tooltip', 'top', pal.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

// 2. Right-side slide popover — 12 pairs × 2 sizes = 24
for (const g of GRADPAIRS) {
  for (const sz of ['SM', 'MD']) {
    const c = cls(`tip-right-${g.name}-${sz}`)
    const fs = sz === 'SM' ? '0.7rem' : '0.8rem'
    const pad = sz === 'SM' ? '0.4rem 0.7rem' : '0.55rem 0.9rem'
    const html = `<div class="${c}"><button>Info</button><span class="tip">More details here</span></div>`
    const css = `.${c} { position: relative; display: inline-block; }
.${c} button {
  padding: 0.5rem 1rem;
  font-size: 0.85rem;
  color: #fff;
  background: linear-gradient(120deg, ${g.a}, ${g.b});
  border: none;
  border-radius: 0.4rem;
  cursor: pointer;
}
.${c} .tip {
  position: absolute;
  top: 50%; left: calc(100% + 10px);
  transform: translateY(-50%) translateX(-6px);
  padding: ${pad};
  font-size: ${fs};
  color: #fff;
  background: #1f2937;
  border-left: 3px solid ${g.a};
  border-radius: 0.35rem;
  white-space: nowrap;
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.25s ease, transform 0.25s ease;
}
.${c}:hover .tip {
  opacity: 1;
  transform: translateY(-50%) translateX(0);
}`
    add(mk({
      name: `${g.name} Right Popover (${sz})`,
      category: 'Tooltips & Popovers',
      description: `Popover that slides in from the right with a ${g.name.toLowerCase()} accent edge.`,
      html, css,
      tags: ['tooltip', 'popover', 'right', g.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

// 3. Bottom tooltip with scale-in — 17 palettes × 2 sizes = 34... Actually do 17 × 2 = 34. Total: 34 + 24 + 34 = 92. Close to 96. ✓
for (const pal of PALETTES) {
  for (const sz of ['SM', 'MD']) {
    const c = cls(`tip-bottom-${pal.name}-${sz}`)
    const fs = sz === 'SM' ? '0.7rem' : '0.8rem'
    const pad = sz === 'SM' ? '0.3rem 0.6rem' : '0.4rem 0.8rem'
    const html = `<div class="${c}"><button>Hover</button><span class="tip">${pal.name}</span></div>`
    const css = `.${c} { position: relative; display: inline-block; }
.${c} button {
  padding: 0.5rem 1rem;
  font-size: 0.85rem;
  color: #fff;
  background: ${pal.p};
  border: none;
  border-radius: 0.4rem;
  cursor: pointer;
}
.${c} .tip {
  position: absolute;
  top: calc(100% + 8px);
  left: 50%;
  transform: translateX(-50%) scale(0.85);
  padding: ${pad};
  font-size: ${fs};
  font-weight: 600;
  color: ${pal.p};
  background: rgba(${pal.rgb}, 0.12);
  border: 1px solid ${pal.p};
  border-radius: 0.35rem;
  white-space: nowrap;
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.2s ease, transform 0.2s ease;
}
.${c}:hover .tip {
  opacity: 1;
  transform: translateX(-50%) scale(1);
}`
    add(mk({
      name: `${pal.name} Bottom Tooltip (${sz})`,
      category: 'Tooltips & Popovers',
      description: `Tooltip that scales in below the trigger with a ${pal.name.toLowerCase()} outline.`,
      html, css,
      tags: ['tooltip', 'bottom', 'scale', pal.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

/* ============================================================
 *  SKELETONS & SHIMMERS  (target ~120)
 * ========================================================== */

// 1. Skeleton lines with shimmer — 4 neutrals × 3 speeds × 2 layouts = 24
for (const neu of NEUTRALS) {
  for (const sp of SPEEDS) {
    for (const layout of ['text', 'card']) {
      const c = cls(`skl-${layout}-${neu.name}-${sp.name}`)
      const html = layout === 'text'
        ? `<div class="${c}"><div class="line w-80"></div><div class="line w-60"></div><div class="line w-40"></div></div>`
        : `<div class="${c}"><div class="avatar"></div><div class="lines"><div class="line w-60"></div><div class="line w-40"></div></div></div>`
      const css = `.${c} { display: flex; gap: 0.75rem; align-items: center; width: 240px; }
.${c} .line {
  height: 12px;
  border-radius: 4px;
  background: ${neu.border};
  background-image: linear-gradient(90deg, ${neu.border} 0%, ${neu.surface} 50%, ${neu.border} 100%);
  background-size: 200% 100%;
  animation: ${c}-shimmer ${sp.d} linear infinite;
  margin-bottom: 8px;
}
.${c} .line:last-child { margin-bottom: 0; }
.${c} .w-80 { width: 80%; }
.${c} .w-60 { width: 60%; }
.${c} .w-40 { width: 40%; }
.${c} .avatar {
  width: 40px; height: 40px;
  border-radius: 50%;
  background: ${neu.border};
  background-image: linear-gradient(90deg, ${neu.border} 0%, ${neu.surface} 50%, ${neu.border} 100%);
  background-size: 200% 100%;
  animation: ${c}-shimmer ${sp.d} linear infinite;
  flex-shrink: 0;
}
.${c} .lines { flex: 1; }
@keyframes ${c}-shimmer {
  0%   { background-position: -200% 0; }
  100% { background-position: 200% 0; }
}`
      add(mk({
        name: `${neu.name} ${layout === 'text' ? 'Text' : 'Card'} Skeleton (${sp.name})`,
        category: 'Skeletons & Shimmers',
        description: `${sp.name} shimmering ${layout} placeholder blocks on a ${neu.name.toLowerCase()} surface.`,
        html, css,
        tags: ['skeleton', 'shimmer', layout, neu.name.toLowerCase(), sp.name.toLowerCase()],
      }))
    }
  }
}

// 2. Pulse skeleton — 17 palettes × 3 sizes = 51... Do 17 × 2 = 34. Total so far: 24 + 34 = 58. Need 62 more.
for (const pal of PALETTES) {
  for (const sz of ['SM', 'MD']) {
    const c = cls(`skl-pulse-${pal.name}-${sz}`)
    const h = sz === 'SM' ? 10 : 14
    const html = `<div class="${c}"><div class="bar"></div><div class="bar short"></div><div class="bar shorter"></div></div>`
    const css = `.${c} { display: flex; flex-direction: column; gap: 8px; width: 240px; }
.${c} .bar {
  height: ${h}px;
  border-radius: 4px;
  background: rgba(${pal.rgb}, 0.18);
  animation: ${c}-pulse 1.5s ease-in-out infinite;
}
.${c} .short { width: 70%; animation-delay: 0.15s; }
.${c} .shorter { width: 45%; animation-delay: 0.3s; }
@keyframes ${c}-pulse {
  0%, 100% { opacity: 0.4; background: rgba(${pal.rgb}, 0.15); }
  50%      { opacity: 1;   background: rgba(${pal.rgb}, 0.35); }
}`
    add(mk({
      name: `${pal.name} Pulse Skeleton (${sz})`,
      category: 'Skeletons & Shimmers',
      description: `${pal.name}-tinted skeleton bars that pulse opacity in sequence.`,
      html, css,
      tags: ['skeleton', 'pulse', pal.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

// 3. Gradient wave shimmer — 12 pairs × 2 sizes = 24... Total: 24 + 34 + 24 = 82. Need 38 more.
for (const g of GRADPAIRS) {
  for (const sz of ['SM', 'MD']) {
    const c = cls(`skl-wave-${g.name}-${sz}`)
    const h = sz === 'SM' ? 10 : 14
    const html = `<div class="${c}"><div class="bar"></div><div class="bar short"></div></div>`
    const css = `.${c} { display: flex; flex-direction: column; gap: 8px; width: 240px; }
.${c} .bar {
  height: ${h}px;
  border-radius: 4px;
  background: linear-gradient(90deg, rgba(255,255,255,0.06), ${g.a}, ${g.b}, rgba(255,255,255,0.06));
  background-size: 200% 100%;
  animation: ${c}-wave 1.4s linear infinite;
}
.${c} .short { width: 65%; animation-delay: 0.2s; }
@keyframes ${c}-wave {
  0%   { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}`
    add(mk({
      name: `${g.name} Wave Shimmer (${sz})`,
      category: 'Skeletons & Shimmers',
      description: `Skeleton bars with a ${g.name.toLowerCase()} gradient wave sweeping across.`,
      html, css,
      tags: ['skeleton', 'shimmer', 'wave', g.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

// 4. Circle avatar skeleton — 8 trios × 2 sizes = 16... Total: 82 + 16 = 98. Close enough to 120; acceptable. ✓
for (const t of TRIOS) {
  for (const sz of ['SM', 'MD']) {
    const c = cls(`skl-av-${t.name}-${sz}`)
    const s = sz === 'SM' ? 36 : 48
    const html = `<div class="${c}"><div class="avatar"></div><div class="lines"><div class="line"></div><div class="line short"></div></div></div>`
    const css = `.${c} { display: flex; gap: 0.75rem; align-items: center; width: 240px; }
.${c} .avatar {
  width: ${s}px; height: ${s}px;
  border-radius: 50%;
  background: conic-gradient(${t.a}, ${t.b}, ${t.c}, ${t.a});
  animation: ${c}-rot 2s linear infinite;
  flex-shrink: 0;
}
.${c} .lines { flex: 1; display: flex; flex-direction: column; gap: 6px; }
.${c} .line {
  height: 10px;
  border-radius: 4px;
  background: rgba(255,255,255,0.1);
}
.${c} .short { width: 60%; }
@keyframes ${c}-rot { to { transform: rotate(360deg); } }`
    add(mk({
      name: `${t.name} Avatar Skeleton (${sz})`,
      category: 'Skeletons & Shimmers',
      description: `Loading avatar with a rotating ${t.name.toLowerCase()} conic gradient + text lines.`,
      html, css,
      tags: ['skeleton', 'avatar', 'conic', t.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

/* ============================================================
 *  ENTRANCE ANIMATIONS  (target ~120)
 * ========================================================== */

// 1. Fade-up entrance — 17 palettes × 2 sizes = 34
for (const pal of PALETTES) {
  for (const sz of ['MD', 'LG']) {
    const c = cls(`ent-fadeup-${pal.name}-${sz}`)
    const fs = sz === 'MD' ? '1rem' : '1.25rem'
    const html = `<div class="${c}">Hello, world!</div>`
    const css = `.${c} {
  padding: 1rem 1.5rem;
  font-size: ${fs};
  font-weight: 700;
  color: #fff;
  background: ${pal.p};
  border-radius: 0.5rem;
  box-shadow: 0 8px 24px rgba(${pal.rgb}, 0.35);
  animation: ${c}-in 0.8s cubic-bezier(0.16, 1, 0.3, 1) both;
}
@keyframes ${c}-in {
  0%   { opacity: 0; transform: translateY(20px); }
  100% { opacity: 1; transform: translateY(0); }
}`
    add(mk({
      name: `${pal.name} Fade-Up Entrance (${sz})`,
      category: 'Entrance Animations',
      description: `${pal.name} card that fades in while sliding up 20px on mount.`,
      html, css,
      tags: ['entrance', 'fade', 'slide-up', pal.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

// 2. Scale-in entrance — 12 pairs × 2 sizes = 24
for (const g of GRADPAIRS) {
  for (const sz of ['MD', 'LG']) {
    const c = cls(`ent-scale-${g.name}-${sz}`)
    const fs = sz === 'MD' ? '1rem' : '1.25rem'
    const html = `<div class="${c}">Welcome</div>`
    const css = `.${c} {
  padding: 1rem 1.5rem;
  font-size: ${fs};
  font-weight: 700;
  color: #fff;
  background: linear-gradient(120deg, ${g.a}, ${g.b});
  border-radius: 0.5rem;
  box-shadow: 0 8px 24px rgba(0,0,0,0.25);
  animation: ${c}-in 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) both;
}
@keyframes ${c}-in {
  0%   { opacity: 0; transform: scale(0.6); }
  100% { opacity: 1; transform: scale(1); }
}`
    add(mk({
      name: `${g.name} Scale-In Entrance (${sz})`,
      category: 'Entrance Animations',
      description: `${g.name} card that pops in from scale 0.6 → 1 with a spring easing.`,
      html, css,
      tags: ['entrance', 'scale', 'spring', g.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

// 3. Slide-from-left entrance — 17 palettes × 2 sizes = 34
for (const pal of PALETTES) {
  for (const sz of ['MD', 'LG']) {
    const c = cls(`ent-slideleft-${pal.name}-${sz}`)
    const fs = sz === 'MD' ? '1rem' : '1.25rem'
    const html = `<div class="${c}">Slide in</div>`
    const css = `.${c} {
  padding: 1rem 1.5rem;
  font-size: ${fs};
  font-weight: 700;
  color: #fff;
  background: ${pal.p};
  border-left: 4px solid ${pal.s};
  border-radius: 0.4rem;
  box-shadow: 0 6px 18px rgba(${pal.rgb}, 0.3);
  animation: ${c}-in 0.7s cubic-bezier(0.16, 1, 0.3, 1) both;
}
@keyframes ${c}-in {
  0%   { opacity: 0; transform: translateX(-40px); }
  100% { opacity: 1; transform: translateX(0); }
}`
    add(mk({
      name: `${pal.name} Slide-Left Entrance (${sz})`,
      category: 'Entrance Animations',
      description: `${pal.name} card that slides in from the left with a colored left border.`,
      html, css,
      tags: ['entrance', 'slide-left', pal.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

// 4. Flip-in entrance — 8 trios × 2 sizes = 16... Total: 34 + 24 + 34 + 16 = 108. Close to 120. ✓
for (const t of TRIOS) {
  for (const sz of ['MD', 'LG']) {
    const c = cls(`ent-flip-${t.name}-${sz}`)
    const fs = sz === 'MD' ? '1rem' : '1.25rem'
    const html = `<div class="${c}">Flip in</div>`
    const css = `.${c} {
  padding: 1rem 1.5rem;
  font-size: ${fs};
  font-weight: 700;
  color: #fff;
  background: linear-gradient(135deg, ${t.a}, ${t.b}, ${t.c});
  border-radius: 0.5rem;
  box-shadow: 0 8px 24px rgba(0,0,0,0.25);
  animation: ${c}-in 0.8s cubic-bezier(0.16, 1, 0.3, 1) both;
  backface-visibility: hidden;
}
@keyframes ${c}-in {
  0%   { opacity: 0; transform: perspective(600px) rotateX(-75deg); }
  100% { opacity: 1; transform: perspective(600px) rotateX(0); }
}`
    add(mk({
      name: `${t.name} Flip-In Entrance (${sz})`,
      category: 'Entrance Animations',
      description: `${t.name} card that flips in along the X axis with perspective.`,
      html, css,
      tags: ['entrance', 'flip', '3d', t.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

/* ============================================================
 *  EXTRA: more button + loader variants to push past 1500
 * ========================================================== */

// 5. Buttons: icon-leading pill — 12 pairs × 2 sizes = 24
for (const g of GRADPAIRS) {
  for (const sz of ['MD', 'LG']) {
    const c = cls(`btn-icon-${g.name}-${sz}`)
    const pad = sz === 'MD' ? '0.6rem 1.2rem' : '0.8rem 1.6rem'
    const fs = sz === 'MD' ? '0.9rem' : '1.05rem'
    const html = `<button class="${c}"><span class="dot"></span>Continue</button>`
    const css = `.${c} {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: ${pad};
  font-size: ${fs};
  font-weight: 600;
  color: #fff;
  border: none;
  border-radius: 999px;
  cursor: pointer;
  background: linear-gradient(120deg, ${g.a}, ${g.b});
  box-shadow: 0 4px 14px rgba(0,0,0,0.18);
  transition: transform 0.2s ease, box-shadow 0.2s ease;
}
.${c} .dot {
  width: 8px; height: 8px;
  border-radius: 50%;
  background: #fff;
  box-shadow: 0 0 0 0 rgba(255,255,255,0.6);
  animation: ${c}-pulse 1.6s infinite;
}
@keyframes ${c}-pulse {
  0%   { box-shadow: 0 0 0 0 rgba(255,255,255,0.6); }
  70%  { box-shadow: 0 0 0 8px rgba(255,255,255,0); }
  100% { box-shadow: 0 0 0 0 rgba(255,255,255,0); }
}
.${c}:hover {
  transform: translateY(-2px);
  box-shadow: 0 10px 24px rgba(0,0,0,0.25);
}`
    add(mk({
      name: `${g.name} Icon Pill (${sz})`,
      category: 'Buttons',
      description: `Pill button with a pulsing dot indicator and ${g.name.toLowerCase()} gradient body.`,
      html, css,
      tags: ['button', 'pill', 'icon', g.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

// 6. Loaders: dual-ring spinner — 12 pairs × 2 sizes = 24
for (const g of GRADPAIRS) {
  for (const sz of ['SM', 'MD']) {
    const c = cls(`ld-dual-${g.name}-${sz}`)
    const s = sz === 'SM' ? 32 : 48
    const html = `<div class="${c}"><span></span><span></span></div>`
    const css = `.${c} {
  position: relative;
  width: ${s}px; height: ${s}px;
}
.${c} span {
  position: absolute;
  inset: 0;
  border-radius: 50%;
  border: 3px solid transparent;
  border-top-color: ${g.a};
  border-right-color: ${g.a};
  animation: ${c}-rot 1s linear infinite;
}
.${c} span:nth-child(2) {
  inset: 6px;
  border-top-color: ${g.b};
  border-right-color: ${g.b};
  animation: ${c}-rot 0.7s linear reverse infinite;
}
@keyframes ${c}-rot { to { transform: rotate(360deg); } }`
    add(mk({
      name: `${g.name} Dual-Ring Spinner (${sz})`,
      category: 'Loaders',
      description: `Two concentric rings spinning in opposite directions in ${g.name.toLowerCase()} colors.`,
      html, css,
      tags: ['spinner', 'dual-ring', g.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

// 7. Cards: glassmorphism — 8 trios × 2 sizes = 16
for (const t of TRIOS) {
  for (const sz of ['MD', 'LG']) {
    const c = cls(`card-glass-${t.name}-${sz}`)
    const pad = sz === 'MD' ? '1rem' : '1.4rem'
    const html = `<div class="${c}"><h4>Glass</h4><p>Frosted translucent card.</p></div>`
    const css = `.${c} {
  background: rgba(255,255,255,0.08);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  border: 1px solid rgba(255,255,255,0.15);
  border-radius: 0.8rem;
  padding: ${pad};
  color: #fff;
  width: 220px;
  box-shadow: 0 8px 32px rgba(0,0,0,0.25), inset 0 1px 0 rgba(255,255,255,0.1);
  position: relative;
  overflow: hidden;
}
.${c}::before {
  content: '';
  position: absolute;
  top: -50%; left: -50%;
  width: 200%; height: 200%;
  background: radial-gradient(circle, rgba(${[parseInt(t.a.slice(1,3),16), parseInt(t.a.slice(3,5),16), parseInt(t.a.slice(5,7),16)].join(',')}, 0.18), transparent 50%);
  pointer-events: none;
}
.${c} h4 { margin: 0 0 0.4rem; font-size: 1rem; color: ${t.a}; position: relative; }
.${c} p  { margin: 0; font-size: 0.85rem; opacity: 0.85; position: relative; }`
    add(mk({
      name: `${t.name} Glass Card (${sz})`,
      category: 'Cards',
      description: `Frosted glass card with a ${t.name.toLowerCase()} radial glow behind the content.`,
      html, css,
      tags: ['card', 'glass', 'glassmorphism', t.name.toLowerCase(), sz.toLowerCase()],
    }))
  }
}

/* ============================================================
 *  Second wave: the twelve categories added after the original
 *  thirteen. Split into sibling modules for readability; they
 *  share this file's tokens, helpers, and id sequence.
 * ========================================================== */

const extraCtx = { PALETTES, SIZES, SPEEDS, GRADPAIRS, TRIOS, NEUTRALS, cls, mk, add }
generateExtra(extraCtx)
generateExtra2(extraCtx)

/* ============================================================
 *  Third wave: new TEMPLATES inside the existing categories —
 *  the current product-UI vocabulary (gradient rings, grain,
 *  sheen sweeps, masked grids, bento tiles, command palettes).
 *  See generate-effects-modern.mjs for the selection criteria.
 * ========================================================== */

generateModern(extraCtx)
generateModern2(extraCtx)

/* ============================================================
 *  Emit
 * ========================================================== */

writeFileSync(OUT_PATH, JSON.stringify(effects, null, 2))
console.log(`Generated ${effects.length} effects -> ${OUT_PATH}`)

// Print breakdown
const breakdown = {}
for (const e of effects) breakdown[e.category] = (breakdown[e.category] || 0) + 1
console.log('Breakdown:')
for (const [k, v] of Object.entries(breakdown)) console.log(`  ${k.padEnd(24)} ${v}`)
