/**
 * Animated icons — the icon browser crossed with the catalog's motion model.
 *
 * Preline ships 100 animated icons. Every set like it is a folder of 100
 * hand-made files, which has two consequences nobody mentions: the motion you
 * want is only available on the icons somebody already drew it for, and the
 * icon you need is only available with the motions somebody already thought
 * of. A 100-file set is not 100 choices, it is 100 *pairs*.
 *
 * This is the crossing instead. 136 icons from `/tools/icons` and twelve
 * motion families, emitted by one renderer, which makes every pair available
 * and makes the set's size a multiplication rather than a headcount.
 *
 * Three things follow from doing it as a crossing, and they are the reason
 * this is worth building rather than copying:
 *
 * 1. **The motion is applied per path, not to a box.** Rotating the whole
 *    `<svg>` is what a CSS one-liner does and it is why most "animated icon"
 *    demos look like a loading spinner wearing an icon. Lucide icons are two
 *    to six separate shapes, and the geometry arrives here as that list — so
 *    a bell can draw itself on stroke by stroke, in order, with a stagger.
 *    Four of the twelve families exist only because the parts are addressable.
 *
 * 2. **`prefers-reduced-motion` is not optional and not an afterthought.**
 *    Eight families are guarded by `reducedMotionGuard` from
 *    `keyframes-css.ts` — the same function the catalog's own effects are
 *    guarded by, called rather than reimplemented, so the rule here cannot
 *    drift from the rule there. The four dash families need more than that
 *    function can express, and the extra is explained where it is emitted.
 *
 * 3. **The keyframes come from the same model `/tools/keyframes` edits.**
 *    Nine families are an `Animation` (see `keyframes-css.ts`) and their CSS
 *    is *derived*; three are hand-written because the timeline model has no
 *    `stroke-dashoffset` and no `rotateY`, and they say so rather than being
 *    approximated into something subtly different. That split, and the reason
 *    for it, is lifted from `motion-presets.ts`, which made the same call.
 *
 * Pure string building over plain data, no DOM and no React — so it runs in
 * the route handler that serves a download, in the Node test runner, and in
 * the browser panel, from one implementation.
 *
 * Icon geometry is ISC-licensed from Lucide and regenerated by
 * `scripts/build-icon-nodes.mjs`. The notice travels with it.
 */

import {
  animationShorthand,
  keyframesBlock,
  loops,
  reducedMotionGuard,
  stopAt,
  withIds,
  type Animation,
} from '../keyframes-css'
import { svgToJsx } from '../svg-tools'
import {
  componentName,
  paletteById,
  svgDocument,
  type AssetScheme,
} from './asset-types'
import generated from './generated-icon-nodes.json'

/* ============================================================
 *  Geometry
 * ============================================================ */

/** One drawable element of an icon: a tag and its attributes. */
export type IconNode = [string, Record<string, string | number>]

export interface IconGeometry {
  /** The Lucide export name, as the icon browser lists it. */
  name: string
  /** Lucide's own file stem. Stable across renames of the export. */
  slug: string
  keywords: string
  nodes: IconNode[]
}

export const ICON_GEOMETRY: IconGeometry[] = generated.icons as IconGeometry[]
export const ICON_LICENSE = generated.license
export const LUCIDE_VERSION = generated.lucideVersion

export function iconBySlug(slug: string): IconGeometry | undefined {
  return ICON_GEOMETRY.find((i) => i.slug === slug)
}

/**
 * Lucide's own root attributes, restated.
 *
 * They are defaults inside the React component and therefore invisible in the
 * geometry, but an icon emitted without them is a black blob: `fill="none"`
 * is what keeps a stroked outline from filling, and the two `linecap` values
 * are most of what makes a Lucide icon look like one. Restating them is the
 * price of emitting files rather than elements.
 */
export const ICON_ROOT_ATTRS = {
  fill: 'none',
  stroke: 'currentColor',
  'stroke-linecap': 'round',
  'stroke-linejoin': 'round',
} as const

/* ============================================================
 *  Families
 * ============================================================ */

export type IconMotionId =
  | 'draw'
  | 'trace'
  | 'fade-stagger'
  | 'pop'
  | 'fade-in'
  | 'spin'
  | 'swing'
  | 'pulse'
  | 'bounce'
  | 'shake'
  | 'float'
  | 'flip'

export type IconMotionGroup = 'Enter' | 'Attention' | 'Loop'

export interface IconMotion {
  id: IconMotionId
  name: string
  group: IconMotionGroup
  /** What this one is for — the reason to pick it over the next one. */
  note: string
  /**
   * True when the animation is applied to each of the icon's shapes in turn
   * rather than to the icon as a whole. These are the families a folder of
   * pre-made files cannot offer, because they need the parts.
   */
  perPath: boolean
  /**
   * How the family uses `stroke-dasharray`, if at all.
   *
   * `draw` hides the stroke and reveals it; `march` leaves a gap travelling
   * along it forever. Both set static properties that the reduced-motion
   * guard then has to undo — see `guardFor`.
   */
  dash: 'draw' | 'march' | null
  /** Default duration in ms. The UI opens here. */
  duration: number
  /** Default per-shape stagger in ms. Meaningless when `perPath` is false. */
  stagger: number
  /**
   * The editable form. Present on everything the timeline model can express,
   * and when it is present the keyframes below are generated from it.
   */
  anim?: Animation
  /** Keyframes body. Only for the families the model cannot express. */
  frames?: string
  /** Easing, for the hand-written families. */
  easing?: string
  /** Loops forever. Only for the hand-written families. */
  forever?: boolean
  /**
   * Whether the animation should hold its last frame.
   *
   * True for anything that *arrives* somewhere — without it a delayed enter
   * animation shows its end state, waits, then jumps back to the start to
   * play, which reads as a flicker. False for attention motions, which are
   * supposed to end where they began.
   */
  holds: boolean
}

const ease = 'cubic-bezier(0.22, 1, 0.36, 1)'

/** An `Animation` from stops, with the fields every family here shares. */
function anim(
  stops: Parameters<typeof withIds>[0],
  over: Partial<Omit<Animation, 'stops'>> = {},
): Animation {
  return {
    duration: 600,
    delay: 0,
    easing: ease,
    iterations: 1,
    direction: 'normal',
    fill: 'none',
    ...over,
    stops: withIds(stops),
  }
}

export const ICON_MOTIONS: IconMotion[] = [
  {
    id: 'draw',
    name: 'Draw on',
    group: 'Enter',
    note: 'Each stroke draws itself, in the order the icon is built. The one that reads as craft rather than as decoration, and the reason this set needed the geometry rather than the component.',
    perPath: true,
    dash: 'draw',
    duration: 700,
    stagger: 120,
    // `stroke-dashoffset` is not on the timeline model — there is no stop
    // field for it and adding one would mean a property only icons can use.
    frames: '  0% {\n    stroke-dashoffset: 1;\n  }\n  100% {\n    stroke-dashoffset: 0;\n  }',
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    holds: true,
  },
  {
    id: 'trace',
    name: 'Trace',
    group: 'Loop',
    note: 'A gap travels along every stroke forever. Reads as "working" without the spinner’s promise that something will finish.',
    perPath: true,
    dash: 'march',
    duration: 2400,
    stagger: 0,
    frames: '  0% {\n    stroke-dashoffset: 0;\n  }\n  100% {\n    stroke-dashoffset: -1.22;\n  }',
    easing: 'linear',
    forever: true,
    holds: false,
  },
  {
    id: 'fade-stagger',
    name: 'Fade in, staggered',
    group: 'Enter',
    note: 'The quietest of the per-path families: the shapes appear in turn. Right where the icon is beside text and a drawing motion would pull the eye off the sentence.',
    perPath: true,
    dash: null,
    duration: 420,
    stagger: 90,
    anim: anim([stopAt(0, { opacity: 0 }), stopAt(100)], { duration: 420, fill: 'both' }),
    holds: true,
  },
  {
    id: 'pop',
    name: 'Pop in',
    group: 'Enter',
    note: 'Scale up past the target and settle. The default for an icon that appears in response to something the reader just did.',
    perPath: false,
    dash: null,
    duration: 420,
    stagger: 0,
    anim: anim(
      [stopAt(0, { opacity: 0, scale: 60 }), stopAt(60, { scale: 108 }), stopAt(100)],
      { duration: 420, fill: 'both' },
    ),
    holds: true,
  },
  {
    id: 'fade-in',
    name: 'Fade in, up',
    group: 'Enter',
    note: 'Four pixels of travel and an opacity ramp. The one to use when a dozen icons enter at once and twelve pops would be a firework.',
    perPath: false,
    dash: null,
    duration: 380,
    stagger: 0,
    anim: anim([stopAt(0, { opacity: 0, y: 4 }), stopAt(100)], { duration: 380, fill: 'both' }),
    holds: true,
  },
  {
    id: 'spin',
    name: 'Spin',
    group: 'Loop',
    note: 'A full turn, linear, forever. Correct for a refresh or a loader glyph and wrong for everything else, which is most of where it gets used.',
    perPath: false,
    dash: null,
    duration: 1000,
    stagger: 0,
    anim: anim([stopAt(0), stopAt(100, { rotate: 360 })], {
      duration: 1000,
      easing: 'linear',
      iterations: 0,
    }),
    holds: false,
  },
  {
    id: 'swing',
    name: 'Swing',
    group: 'Attention',
    note: 'A pendulum that loses energy. Built for the bell, and the one motion people can name without being told.',
    perPath: false,
    dash: null,
    duration: 900,
    stagger: 0,
    anim: anim(
      [
        stopAt(0),
        stopAt(20, { rotate: -14 }),
        stopAt(40, { rotate: 11 }),
        stopAt(60, { rotate: -7 }),
        stopAt(80, { rotate: 3 }),
        stopAt(100),
      ],
      { duration: 900, easing: 'ease-in-out' },
    ),
    holds: false,
  },
  {
    id: 'pulse',
    name: 'Pulse',
    group: 'Loop',
    note: 'A breathing scale. The honest way to mark something live, as opposed to a red dot that is live whether or not anything is happening.',
    perPath: false,
    dash: null,
    duration: 1800,
    stagger: 0,
    anim: anim([stopAt(0), stopAt(50, { scale: 112 }), stopAt(100)], {
      duration: 1800,
      easing: 'ease-in-out',
      iterations: 0,
    }),
    holds: false,
  },
  {
    id: 'bounce',
    name: 'Bounce',
    group: 'Attention',
    note: 'Two hops with the second smaller. For a download that has finished or an inbox that has something new.',
    perPath: false,
    dash: null,
    duration: 800,
    stagger: 0,
    anim: anim(
      [
        stopAt(0),
        stopAt(30, { y: -6 }),
        stopAt(55, { y: 0 }),
        stopAt(75, { y: -3 }),
        stopAt(100),
      ],
      { duration: 800, easing: 'ease-out' },
    ),
    holds: false,
  },
  {
    id: 'shake',
    name: 'Shake',
    group: 'Attention',
    note: 'Horizontal, decaying, over in a third of a second. The refusal gesture — pair it with the error, never with the submit.',
    perPath: false,
    dash: null,
    duration: 420,
    stagger: 0,
    anim: anim(
      [
        stopAt(0),
        stopAt(20, { x: -4 }),
        stopAt(40, { x: 4 }),
        stopAt(60, { x: -3 }),
        stopAt(80, { x: 2 }),
        stopAt(100),
      ],
      { duration: 420, easing: 'ease-in-out' },
    ),
    holds: false,
  },
  {
    id: 'float',
    name: 'Float',
    group: 'Loop',
    note: 'Four pixels, slowly, forever. Ambient rather than attention-seeking — for an empty state, where something has to move or the page looks broken.',
    perPath: false,
    dash: null,
    duration: 3000,
    stagger: 0,
    anim: anim([stopAt(0), stopAt(50, { y: -4 }), stopAt(100)], {
      duration: 3000,
      easing: 'ease-in-out',
      iterations: 0,
    }),
    holds: false,
  },
  {
    id: 'flip',
    name: 'Flip',
    group: 'Attention',
    note: 'A turn about the vertical axis, with perspective. For a state that has just inverted — muted to unmuted, hidden to shown.',
    perPath: false,
    dash: null,
    duration: 700,
    stagger: 0,
    // `rotateY` and `perspective()` are not on the timeline model, which is
    // 2D by construction. Approximating this as a horizontal scale would be a
    // different animation that happens to start and end in the same place.
    frames:
      '  0% {\n    transform: perspective(400px) rotateY(0deg);\n  }\n  100% {\n    transform: perspective(400px) rotateY(360deg);\n  }',
    easing: 'cubic-bezier(0.45, 0, 0.55, 1)',
    holds: false,
  },
]

export const DEFAULT_MOTION_ID: IconMotionId = 'draw'

export function motionById(id: string): IconMotion {
  return ICON_MOTIONS.find((m) => m.id === id) ?? ICON_MOTIONS[0]
}

/** 136 icons × 12 motions. The number is a multiplication, and says so. */
export function animatedIconCount(): number {
  return ICON_GEOMETRY.length * ICON_MOTIONS.length
}

/* ============================================================
 *  Emitting
 * ============================================================ */

export type IconTrigger = 'load' | 'hover'

export interface AnimatedIconOptions {
  icon: IconGeometry
  motion: IconMotionId
  /** ms. Defaults to the family's own. */
  duration?: number
  /** ms before the first shape moves. */
  delay?: number
  /** ms between shapes. Ignored by the whole-icon families. */
  stagger?: number
  trigger?: IconTrigger
  /** Rendered px. The viewBox is always 24. */
  size?: number
  strokeWidth?: number
}

interface Resolved extends Required<Omit<AnimatedIconOptions, 'icon' | 'motion'>> {
  icon: IconGeometry
  family: IconMotion
}

function resolve(options: AnimatedIconOptions): Resolved {
  const family = motionById(options.motion)
  return {
    icon: options.icon,
    family,
    duration: options.duration ?? family.duration,
    delay: options.delay ?? 0,
    stagger: options.stagger ?? family.stagger,
    trigger: options.trigger ?? 'load',
    size: options.size ?? 48,
    strokeWidth: options.strokeWidth ?? 2,
  }
}

/**
 * The class, which is also the `@keyframes` name.
 *
 * Keyed on the family and not on the icon, deliberately. Twelve stylesheets
 * serve all 1,632 combinations, so taking four icons with the same motion is
 * four elements and one rule — whereas a per-icon class would have the reader
 * paste four near-identical keyframe blocks and then maintain them.
 */
export function motionClass(id: IconMotionId): string {
  return `hl-icon-${id}`
}

/** The class on each shape of a per-path icon. */
export const PATH_CLASS = 'hl-shape'

function shorthandFor(r: Resolved): string {
  const f = r.family
  const forever = f.anim ? loops(f.anim) : Boolean(f.forever)
  return animationShorthand({
    duration: r.duration,
    // The delay is emitted by the rule, not the shorthand: a staggered family
    // needs `calc()`, which a shorthand cannot carry.
    delay: 0,
    easing: f.anim?.easing ?? f.easing ?? ease,
    iterations: forever ? 0 : 1,
    direction: 'normal',
    fill: f.holds ? 'both' : 'none',
    stops: [],
  })
}

function framesFor(r: Resolved): string {
  const name = motionClass(r.family.id)
  if (r.family.anim) return keyframesBlock(name, r.family.anim.stops)
  return `@keyframes ${name} {\n${r.family.frames}\n}`
}

/**
 * The static properties a dash family needs before it can animate.
 *
 * `pathLength="1"` on every shape is what makes one dash length work for all
 * 136 icons: it renormalises the path's own length to 1, so `dasharray: 1`
 * is "exactly one stroke" whether the shape is a 3px tick or a 60px outline.
 * Measuring each path instead would mean a DOM, which would mean this module
 * could not run in Node or emit a file.
 */
function dashDeclarations(family: IconMotion): string[] {
  if (family.dash === 'draw') return ['stroke-dasharray: 1;', 'stroke-dashoffset: 1;']
  if (family.dash === 'march') return ['stroke-dasharray: 0.22 1;']
  return []
}

/**
 * The reduced-motion guard, which is two different problems.
 *
 * For the eight whole-icon families it is exactly `reducedMotionGuard` from
 * `keyframes-css.ts`, called rather than copied, so the site cannot end up
 * handing out two different ideas of what the guard is. A test asserts that
 * equality.
 *
 * The four per-path families need more, for a reason the function cannot know
 * about: they animate a descendant, and two of them set static properties.
 * A `draw` icon whose animation is merely disabled is left at
 * `stroke-dashoffset: 1` — which is an **invisible icon**, on the one setting
 * that exists to help. Collapsing the duration lands it at its final frame,
 * but that still assumes the animation runs at all, and "disable animations"
 * extensions are common enough that assuming it is a bad bet. So the guard
 * also undoes the dash properties outright: with no animation of any kind,
 * the icon is simply itself.
 */
export function guardFor(family: IconMotion): string {
  const cls = motionClass(family.id)
  const looping = family.anim ? loops(family.anim) : Boolean(family.forever)
  if (!family.perPath) return reducedMotionGuard(cls, looping)

  const lines = [
    looping
      ? '    animation: none;'
      : '    animation-duration: 0.01ms !important;\n    animation-iteration-count: 1 !important;',
  ]
  if (family.dash) lines.push('    stroke-dasharray: none;', '    stroke-dashoffset: 0;')
  if (family.id === 'fade-stagger') lines.push('    opacity: 1;')
  return `@media (prefers-reduced-motion: reduce) {\n  .${cls} .${PATH_CLASS} {\n${lines.join('\n')}\n  }\n}`
}

/**
 * The stylesheet for one pairing.
 *
 * Depends on the family and the timing, never on which icon — see
 * `motionClass`. Ordered keyframes, rule, guard, which is the order
 * `buildAnimationCss` uses for the catalog's effects.
 */
export function buildAnimatedIconCss(options: AnimatedIconOptions): string {
  const r = resolve(options)
  const f = r.family
  const cls = motionClass(f.id)
  const target = f.perPath ? `.${cls} .${PATH_CLASS}` : `.${cls}`
  /*
    `:focus-visible` beside `:hover`, always.

    An icon whose motion is the feedback for an interaction has to reach a
    keyboard. It costs one selector and it is the single most commonly
    skipped line in every hover-animation snippet on the web.
  */
  const selector =
    r.trigger === 'hover'
      ? f.perPath
        ? `.${cls}:hover .${PATH_CLASS}, .${cls}:focus-visible .${PATH_CLASS}`
        : `.${cls}:hover, .${cls}:focus-visible`
      : target

  const delay =
    f.perPath && r.stagger
      ? `calc(${r.delay}ms + var(--i, 0) * ${r.stagger}ms)`
      : `${r.delay}ms`

  const statics = dashDeclarations(f)
  const blocks: string[] = [framesFor(r)]

  /*
    A dash family's static properties go on the shapes unconditionally, not
    inside the `:hover` rule. Putting them in the hover rule would mean the
    icon is fully drawn until the pointer arrives and then vanishes to redraw
    — a flicker rather than an animation.

    On `load` that lands them on the same selector as the animation, so the
    two are emitted as one rule. Two adjacent blocks with an identical
    selector is not wrong, but it is the kind of output that makes a reader
    check whether the generator is confused.
  */
  const sharesSelector = statics.length > 0 && selector === target
  if (statics.length && !sharesSelector) {
    blocks.push(`.${cls} .${PATH_CLASS} {\n${statics.map((d) => `  ${d}`).join('\n')}\n}`)
  }

  const rule = [`${selector} {`]
  if (sharesSelector) rule.push(...statics.map((d) => `  ${d}`))
  rule.push(`  animation: ${cls} ${shorthandFor(r)};`)
  if (r.delay || (f.perPath && r.stagger)) rule.push(`  animation-delay: ${delay};`)
  rule.push('}')
  blocks.push(rule.join('\n'))
  blocks.push(guardFor(f))
  return blocks.join('\n\n')
}

function serializeAttrs(attrs: Record<string, string | number>): string {
  return Object.entries(attrs)
    .map(([k, v]) => ` ${k}="${v}"`)
    .join('')
}

/**
 * The icon's shapes, classed and indexed.
 *
 * `--i` on each shape rather than `:nth-child()` for the stagger, because an
 * SVG's children are not only its shapes: a `<title>` and a `<style>` are
 * children too, and both shift every positional selector by one. Worse, they
 * do so only in the standalone file — so the `:nth-child` version works in
 * the React component, breaks in the download, and looks like a file
 * corruption rather than a selector bug.
 */
function shapes(r: Resolved): string {
  const f = r.family
  return r.icon.nodes
    .map(([tag, attrs], i) => {
      const extra: Record<string, string | number> = {}
      if (f.perPath) {
        extra.class = PATH_CLASS
        if (r.stagger) extra.style = `--i:${i}`
        if (f.dash) extra.pathLength = 1
      }
      return `  <${tag}${serializeAttrs(attrs)}${serializeAttrs(extra)} />`
    })
    .join('\n')
}

export interface MarkupOptions extends AnimatedIconOptions {
  /**
   * A file that has to animate on its own.
   *
   * The stylesheet and a resolved `color` go inside the document, because an
   * `.svg` on disk has no page to inherit either from — `currentColor` in a
   * standalone file resolves to the renderer's default text colour, which is
   * black on every background including a dark one. Inline markup must NOT
   * carry either: a `<style>` with a bare `.hl-icon-draw` rule inside a page
   * is a global stylesheet smuggled in through an icon, and a hard-coded
   * `color` would override the `text-*` class that is meant to colour it.
   */
  standalone?: boolean
  /** Only used when standalone, to pick the two `color` values. */
  paletteId?: string
  /** Only used when standalone. */
  scheme?: AssetScheme
  /**
   * The accessible name, or `null` for a decorative icon.
   *
   * Defaults to null for inline markup and to the icon's name for a file —
   * which is the right way round. An icon beside its own label is decorative
   * and a second announcement is noise; a file someone downloads has no
   * label anywhere near it.
   */
  title?: string | null
}

export function buildAnimatedIconSvg(options: MarkupOptions): string {
  const r = resolve(options)
  const standalone = options.standalone ?? false
  const cls = motionClass(r.family.id)

  const rootAttrs = [
    ...Object.entries(ICON_ROOT_ATTRS).map(([k, v]) => ` ${k}="${v}"`),
    ` stroke-width="${r.strokeWidth}"`,
    ` class="${cls}"`,
  ].join('')

  let style = ''
  if (standalone) {
    const palette = paletteById(options.paletteId ?? 'slate')
    const scheme = options.scheme ?? 'auto'
    const css = buildAnimatedIconCss(options)
      .split('\n')
      .map((l) => (l ? `    ${l}` : l))
      .join('\n')
    const colorRule = (ink: string) => `    :root { color: ${ink}; }`
    const colors =
      scheme === 'auto'
        ? [
            colorRule(palette.light.ink),
            '    @media (prefers-color-scheme: dark) {',
            `  ${colorRule(palette.dark.ink)}`,
            '    }',
          ].join('\n')
        : colorRule(scheme === 'dark' ? palette.dark.ink : palette.light.ink)
    style = `  <style>\n${colors}\n${css}\n  </style>`
  }

  return svgDocument({
    viewBox: '0 0 24 24',
    size: r.size,
    body: shapes(r),
    style,
    title: options.title === undefined ? (standalone ? r.icon.name : null) : options.title,
    rootAttrs,
  })
}

/**
 * The pairing as a React component.
 *
 * Markup only — the stylesheet is handed over separately rather than stuffed
 * into a `<style>` inside the component. Twelve components importing twelve
 * copies of the same rule is how a design system ends up with the same
 * keyframes defined forty times, and the class is shared precisely so that it
 * is defined once in the project's own stylesheet.
 */
export function buildAnimatedIconJsx(options: MarkupOptions): string {
  const r = resolve(options)
  const cls = motionClass(r.family.id)
  const svg = buildAnimatedIconSvg({ ...options, standalone: false })
  const jsx = svgToJsx(svg, {
    componentName: componentName(r.icon.name, r.family.id, 'icon'),
    typescript: true,
    currentColor: false,
    spreadProps: true,
  })

  return (
    jsx
      /*
        `svgToJsx` spreads `...props` first, which is right for every other
        caller and wrong here: the motion class is the whole point of the
        component, so it must not be overwritten — and `className` is also the
        first prop anyone passes an icon, so it must not be thrown away. The
        generic emitter cannot merge two values; this caller can.
      */
      .replace(
        `className="${cls}"`,
        `className={['${cls}', props.className].filter(Boolean).join(' ')}`,
      )
      /*
        A custom property in a style object is valid React and invalid
        `CSSProperties` — TypeScript rejects `{ '--i': 0 }` outright. The cast
        is what every codebase ends up writing by hand, so the snippet ships
        with it rather than handing out something that does not compile.
      */
      .replace(/style=\{\{ '--i': '(\d+)' \}\}/g, "style={{ '--i': $1 } as React.CSSProperties}")
  )
}

/** What the download is called. `bell-draw.svg`. */
export function animatedIconFileName(icon: IconGeometry, motion: IconMotionId): string {
  return `${icon.slug}-${motion}.svg`
}

/** Search over name and keywords, the same fields the icon browser matches. */
export function searchIcons(query: string): IconGeometry[] {
  const q = query.trim().toLowerCase()
  if (!q) return ICON_GEOMETRY
  return ICON_GEOMETRY.filter(
    (i) =>
      i.name.toLowerCase().includes(q) ||
      i.slug.includes(q) ||
      i.keywords.toLowerCase().includes(q),
  )
}
